window.CATEGORIES = [
  { id: "airport", name: "机场与交通", icon: "✈️" },
  { id: "hotel", name: "住宿", icon: "🏨" },
  { id: "food", name: "餐饮", icon: "🍜" },
  { id: "shopping", name: "购物", icon: "🛍️" },
  { id: "directions", name: "问路与方向", icon: "🧭" },
  { id: "numbers", name: "数字、时间与日期", icon: "🕐" },
  { id: "emergency", name: "紧急与健康", icon: "🆘" },
  { id: "expressions", name: "常用表达与礼貌用语", icon: "💬" }
];

window.WORD_BANK = (function () {
  const groups = {
    airport: [
      ["护照", "パスポート", "ぱすぽーと", "passport", "word"],
      ["签证", "ビザ", "びざ", "visa", "word"],
      ["机票", "航空券", "こうくうけん", "airline ticket", "word"],
      ["登机牌", "搭乗券", "とうじょうけん", "boarding pass", "word"],
      ["行李", "荷物", "にもつ", "luggage", "word"],
      ["行李箱", "スーツケース", "すーつけーす", "suitcase", "word"],
      ["手提行李", "機内持ち込み手荷物", "きないもちこみてにもつ", "carry-on baggage", "word"],
      ["机场", "空港", "くうこう", "airport", "word"],
      ["航站楼", "ターミナル", "たーみなる", "terminal", "word"],
      ["出发", "出発", "しゅっぱつ", "departure", "word"],
      ["到达", "到着", "とうちゃく", "arrival", "word"],
      ["登机口", "搭乗口", "とうじょうぐち", "boarding gate", "word"],
      ["安检", "保安検査", "ほあんけんさ", "security check", "word"],
      ["海关", "税関", "ぜいかん", "customs", "word"],
      ["入境", "入国", "にゅうこく", "entry", "word"],
      ["出境", "出国", "しゅっこく", "departure", "word"],
      ["转机", "乗り継ぎ", "のりつぎ", "transfer", "word"],
      ["航班", "便", "びん", "flight", "word"],
      ["延误", "遅延", "ちえん", "delay", "word"],
      ["取消", "キャンセル", "きゃんせる", "cancellation", "word"],
      ["值机", "チェックイン", "ちぇっくいん", "check-in", "word"],
      ["登机", "搭乗", "とうじょう", "boarding", "word"],
      ["起飞", "離陸", "りりく", "takeoff", "word"],
      ["降落", "着陸", "ちゃくりく", "landing", "word"],
      ["座位", "座席", "ざせき", "seat", "word"],
      ["靠窗座位", "窓側の席", "まどがわのせき", "window seat", "word"],
      ["过道座位", "通路側の席", "つうろがわのせき", "aisle seat", "word"],
      ["行李领取处", "手荷物受取所", "てにもつうけとりじょ", "baggage claim", "word"],
      ["行李推车", "カート", "かーと", "luggage cart", "word"],
      ["护照查验", "パスポートコントロール", "ぱすぽーとこんとろーる", "passport control", "word"],
      ["免税店", "免税店", "めんぜいてん", "duty-free shop", "word"],
      ["机场大巴", "空港バス", "くうこうばす", "airport bus", "word"],
      ["出租车", "タクシー", "たくしー", "taxi", "word"],
      ["地铁", "地下鉄", "ちかてつ", "subway", "word"],
      ["火车", "電車", "でんしゃ", "train", "word"],
      ["高铁", "新幹線", "しんかんせん", "bullet train", "word"],
      ["公交车", "バス", "ばす", "bus", "word"],
      ["车站", "駅", "えき", "station", "word"],
      ["站台", "ホーム", "ほーむ", "platform", "word"],
      ["时刻表", "時刻表", "じこくひょう", "timetable", "word"],
      ["单程票", "片道切符", "かたみちきっぷ", "one-way ticket", "word"],
      ["往返票", "往復切符", "おうふくきっぷ", "round-trip ticket", "word"],
      ["车票", "切符", "きっぷ", "ticket", "word"],
      ["售票处", "切符売り場", "きっぷうりば", "ticket office", "word"],
      ["自动售票机", "自動券売機", "じどうけんばいき", "ticket machine", "word"],
      ["检票口", "改札口", "かいさつぐち", "ticket gate", "word"],
      ["入口", "入口", "いりぐち", "entrance", "word"],
      ["出口", "出口", "でぐち", "exit", "word"],
      ["问讯处", "案内所", "あんないじょ", "information desk", "word"],
      ["地图", "地図", "ちず", "map", "word"],
      ["目的地", "目的地", "もくてきち", "destination", "word"],
      ["汽车", "車", "くるま", "car", "word"],
      ["租车", "レンタカー", "れんたかー", "rental car", "word"],
      ["加油站", "ガソリンスタンド", "がそりんすたんど", "gas station", "word"],
      ["停车场", "駐車場", "ちゅうしゃじょう", "parking lot", "word"],
      ["红绿灯", "信号", "しんごう", "traffic light", "word"],
      ["人行横道", "横断歩道", "おうだんほどう", "crosswalk", "word"],
      ["自行车", "自転車", "じてんしゃ", "bicycle", "word"],
      ["摩托车", "バイク", "ばいく", "motorcycle", "word"],
      ["步行", "徒歩", "とほ", "on foot", "word"],
      ["直飞", "直行便", "ちょっこうびん", "direct flight", "word"],
      ["行李寄存", "荷物預かり", "にもつあずかり", "luggage storage", "word"],
      ["行李丢失", "荷物紛失", "にもつふんしつ", "lost luggage", "word"],
      ["护照号码", "パスポート番号", "ぱすぽーとばんごう", "passport number", "word"],
      ["航班号", "便名", "びんめい", "flight number", "word"],
      ["候机室", "待合室", "まちあいしつ", "waiting room", "word"],
      ["登机时间", "搭乗時刻", "とうじょうじこく", "boarding time", "word"],
      ["随身携带", "持ち込む", "もちこむ", "to carry on", "word"],
      ["托运", "預ける", "あずける", "to check in luggage", "word"],
      ["行李检查", "手荷物検査", "てにもつけんさ", "baggage inspection", "word"],
      ["入境卡", "入国カード", "にゅうこくかーど", "arrival card", "word"],
      ["海关申报", "税関申告", "ぜいかんしんこく", "customs declaration", "word"],
      ["转机柜台", "乗り継ぎカウンター", "のりつぎかうんたー", "transfer counter", "word"],
      ["安全带", "シートベルト", "しーとべると", "seat belt", "word"],
      ["空乘", "客室乗務員", "きゃくしつじょうむいん", "flight attendant", "word"],
      ["机长", "機長", "きちょう", "captain", "word"],
      ["登机桥", "搭乗橋", "とうじょうきょう", "jet bridge", "word"],
      ["跑道", "滑走路", "かっそうろ", "runway", "word"],
      ["签证延期", "ビザ延長", "びざえんちょう", "visa extension", "word"],
      ["入境检查", "入国審査", "にゅうこくしんさ", "immigration inspection", "word"],
      ["行李超重", "超過手荷物", "ちょうかてにもつ", "excess baggage", "word"],
      ["靠窗", "窓側", "まどがわ", "window side", "word"],
      ["靠过道", "通路側", "つうろがわ", "aisle side", "word"],
      ["救生衣", "救命胴衣", "きゅうめいどうい", "life jacket", "word"],
      ["请问在哪里登机？", "搭乗口はどこですか？", "とうじょうぐちはどこですか？", "Where is the boarding gate?", "phrase"],
      ["请问在哪里取行李？", "荷物はどこで受け取りますか？", "にもつはどこでうけとりますか？", "Where can I pick up my luggage?", "phrase"],
      ["我想换乘。", "乗り換えたいです。", "のりかえたいです。", "I want to transfer.", "phrase"]
    ],

    hotel: [
      ["酒店", "ホテル", "ほてる", "hotel", "word"],
      ["日式旅馆", "旅館", "りょかん", "Japanese inn", "word"],
      ["民宿", "民宿", "みんしゅく", "guesthouse", "word"],
      ["前台", "フロント", "ふろんと", "front desk", "word"],
      ["预订", "予約", "よやく", "reservation", "word"],
      ["入住", "チェックイン", "ちぇっくいん", "check-in", "word"],
      ["退房", "チェックアウト", "ちぇっくあうと", "check-out", "word"],
      ["房间", "部屋", "へや", "room", "word"],
      ["单人房", "シングルルーム", "しんぐるるーむ", "single room", "word"],
      ["双人房", "ツインルーム", "ついんるーむ", "twin room", "word"],
      ["大床房", "ダブルルーム", "だぶるるーむ", "double room", "word"],
      ["套房", "スイートルーム", "すいーとるーむ", "suite", "word"],
      ["钥匙", "鍵", "かぎ", "key", "word"],
      ["房卡", "ルームキー", "るーむきー", "room key", "word"],
      ["行李员", "ベルボーイ", "べるぼーい", "bellboy", "word"],
      ["工作人员", "スタッフ", "すたっふ", "staff", "word"],
      ["客房服务", "ルームサービス", "るーむさーびす", "room service", "word"],
      ["打扫", "掃除", "そうじ", "cleaning", "word"],
      ["毛巾", "タオル", "たおる", "towel", "word"],
      ["床单", "シーツ", "しーつ", "bed sheet", "word"],
      ["枕头", "枕", "まくら", "pillow", "word"],
      ["被子", "布団", "ふとん", "futon / duvet", "word"],
      ["毯子", "毛布", "もうふ", "blanket", "word"],
      ["空调", "エアコン", "えあこん", "air conditioner", "word"],
      ["暖气", "暖房", "だんぼう", "heating", "word"],
      ["浴室", "浴室", "よくしつ", "bathroom", "word"],
      ["淋浴", "シャワー", "しゃわー", "shower", "word"],
      ["浴缸", "バスタブ", "ばすたぶ", "bathtub", "word"],
      ["热水", "お湯", "おゆ", "hot water", "word"],
      ["冷水", "冷水", "れいすい", "cold water", "word"],
      ["卫生间", "トイレ", "といれ", "toilet", "word"],
      ["卫生纸", "トイレットペーパー", "といれっとぺーぱー", "toilet paper", "word"],
      ["洗发水", "シャンプー", "しゃんぷー", "shampoo", "word"],
      ["沐浴露", "ボディソープ", "ぼでぃそーぷ", "body soap", "word"],
      ["牙刷", "歯ブラシ", "はぶらし", "toothbrush", "word"],
      ["牙膏", "歯磨き粉", "はみがきこ", "toothpaste", "word"],
      ["吹风机", "ドライヤー", "どらいやー", "hair dryer", "word"],
      ["插座", "コンセント", "こんせんと", "outlet", "word"],
      ["转换插头", "変換プラグ", "へんかんぷらぐ", "plug adapter", "word"],
      ["无线网络", "Wi-Fi", "わいふぁい", "Wi-Fi", "word"],
      ["网络", "インターネット", "いんたーねっと", "internet", "word"],
      ["电梯", "エレベーター", "えれべーたー", "elevator", "word"],
      ["楼梯", "階段", "かいだん", "stairs", "word"],
      ["大堂", "ロビー", "ろびー", "lobby", "word"],
      ["餐厅", "レストラン", "れすとらん", "restaurant", "word"],
      ["早餐", "朝食", "ちょうしょく", "breakfast", "word"],
      ["叫醒服务", "モーニングコール", "もーにんぐこーる", "wake-up call", "word"],
      ["洗衣服务", "ランドリーサービス", "らんどりーさーびす", "laundry service", "word"],
      ["熨斗", "アイロン", "あいろん", "iron", "word"],
      ["保险箱", "セーフティボックス", "せーふてぃぼっくす", "safe box", "word"],
      ["退房时间", "チェックアウト時間", "ちぇっくあうとじかん", "check-out time", "word"],
      ["入住时间", "チェックイン時間", "ちぇっくいんじかん", "check-in time", "word"],
      ["空房", "空室", "くうしつ", "vacant room", "word"],
      ["满房", "満室", "まんしつ", "fully booked", "word"],
      ["押金", "デポジット", "でぽじっと", "deposit", "word"],
      ["收据", "領収書", "りょうしゅうしょ", "receipt", "word"],
      ["账单", "請求書", "せいきゅうしょ", "bill", "word"],
      ["前台电话", "フロント電話", "ふろんとでんわ", "front desk phone", "word"],
      ["烟雾报警器", "火災報知器", "かさいほうちき", "smoke alarm", "word"],
      ["灭火器", "消火器", "しょうかき", "fire extinguisher", "word"],
      ["婴儿床", "ベビーベッド", "べびーべっど", "baby bed", "word"],
      ["加床", "エキストラベッド", "えきすとらべっど", "extra bed", "word"],
      ["床垫", "マットレス", "まっとれす", "mattress", "word"],
      ["冰箱", "冷蔵庫", "れいぞうこ", "refrigerator", "word"],
      ["微波炉", "電子レンジ", "でんしれんじ", "microwave", "word"],
      ["水壶", "ポット", "ぽっと", "kettle", "word"],
      ["杯子", "コップ", "こっぷ", "cup", "word"],
      ["拖鞋", "スリッパ", "すりっぱ", "slippers", "word"],
      ["衣架", "ハンガー", "はんがー", "hanger", "word"],
      ["衣柜", "クローゼット", "くろーぜっと", "closet", "word"],
      ["窗帘", "カーテン", "かーてん", "curtain", "word"],
      ["阳台", "バルコニー", "ばるこにー", "balcony", "word"],
      ["景色", "景色", "けしき", "view", "word"],
      ["安静", "静か", "しずか", "quiet", "word"],
      ["吵闹", "うるさい", "うるさい", "noisy", "word"],
      ["舒适", "快適", "かいてき", "comfortable", "word"],
      ["房间号", "部屋番号", "へやばんごう", "room number", "word"],
      ["续住", "延泊", "えんぱく", "extend stay", "word"],
      ["我把钥匙弄丢了。", "鍵をなくしました。", "かぎをなくしました。", "I lost my key.", "phrase"],
      ["可以寄存行李吗？", "荷物を預かってもらえますか？", "にもつをあずかってもらえますか？", "Can I leave my luggage?", "phrase"],
      ["请问几点退房？", "チェックアウトは何時ですか？", "ちぇっくあうとはなんじですか？", "What time is checkout?", "phrase"],
      ["可以换个房间吗？", "部屋を変えてもらえますか？", "へやをかえてもらえますか？", "Can I change rooms?", "phrase"]
    ],

    food: [
      ["早餐", "朝食", "ちょうしょく", "breakfast", "word"],
      ["午餐", "昼食", "ちゅうしょく", "lunch", "word"],
      ["晚餐", "夕食", "ゆうしょく", "dinner", "word"],
      ["菜单", "メニュー", "めにゅー", "menu", "word"],
      ["点菜", "注文", "ちゅうもん", "order", "word"],
      ["水", "水", "みず", "water", "word"],
      ["热水", "お湯", "おゆ", "hot water", "word"],
      ["茶", "お茶", "おちゃ", "tea", "word"],
      ["咖啡", "コーヒー", "こーひー", "coffee", "word"],
      ["牛奶", "牛乳", "ぎゅうにゅう", "milk", "word"],
      ["果汁", "ジュース", "じゅーす", "juice", "word"],
      ["啤酒", "ビール", "びーる", "beer", "word"],
      ["红酒", "ワイン", "わいん", "wine", "word"],
      ["米饭", "ご飯", "ごはん", "rice", "word"],
      ["面包", "パン", "ぱん", "bread", "word"],
      ["面条", "麺", "めん", "noodles", "word"],
      ["拉面", "ラーメン", "らーめん", "ramen", "word"],
      ["乌冬面", "うどん", "うどん", "udon", "word"],
      ["荞麦面", "そば", "そば", "soba", "word"],
      ["寿司", "寿司", "すし", "sushi", "word"],
      ["生鱼片", "刺身", "さしみ", "sashimi", "word"],
      ["天妇罗", "天ぷら", "てんぷら", "tempura", "word"],
      ["味噌汤", "味噌汁", "みそしる", "miso soup", "word"],
      ["鸡蛋", "卵", "たまご", "egg", "word"],
      ["肉", "肉", "にく", "meat", "word"],
      ["牛肉", "牛肉", "ぎゅうにく", "beef", "word"],
      ["猪肉", "豚肉", "ぶたにく", "pork", "word"],
      ["鸡肉", "鶏肉", "とりにく", "chicken", "word"],
      ["鱼", "魚", "さかな", "fish", "word"],
      ["虾", "海老", "えび", "shrimp", "word"],
      ["螃蟹", "蟹", "かに", "crab", "word"],
      ["蔬菜", "野菜", "やさい", "vegetables", "word"],
      ["水果", "果物", "くだもの", "fruit", "word"],
      ["苹果", "りんご", "りんご", "apple", "word"],
      ["香蕉", "バナナ", "ばなな", "banana", "word"],
      ["橙子", "オレンジ", "おれんじ", "orange", "word"],
      ["草莓", "いちご", "いちご", "strawberry", "word"],
      ["西瓜", "スイカ", "すいか", "watermelon", "word"],
      ["沙拉", "サラダ", "さらだ", "salad", "word"],
      ["汤", "スープ", "すーぷ", "soup", "word"],
      ["汉堡", "ハンバーガー", "はんばーがー", "hamburger", "word"],
      ["炸鸡", "フライドチキン", "ふらいどちきん", "fried chicken", "word"],
      ["薯条", "フライドポテト", "ふらいどぽてと", "french fries", "word"],
      ["披萨", "ピザ", "ぴざ", "pizza", "word"],
      ["三明治", "サンドイッチ", "さんどいっち", "sandwich", "word"],
      ["冰淇淋", "アイスクリーム", "あいすくりーむ", "ice cream", "word"],
      ["蛋糕", "ケーキ", "けーき", "cake", "word"],
      ["甜点", "デザート", "でざーと", "dessert", "word"],
      ["巧克力", "チョコレート", "ちょこれーと", "chocolate", "word"],
      ["糖果", "キャンディー", "きゃんでぃー", "candy", "word"],
      ["盐", "塩", "しお", "salt", "word"],
      ["糖", "砂糖", "さとう", "sugar", "word"],
      ["酱油", "醤油", "しょうゆ", "soy sauce", "word"],
      ["醋", "酢", "す", "vinegar", "word"],
      ["胡椒", "胡椒", "こしょう", "pepper", "word"],
      ["辣椒", "唐辛子", "とうがらし", "chili", "word"],
      ["芥末", "わさび", "わさび", "wasabi", "word"],
      ["筷子", "箸", "はし", "chopsticks", "word"],
      ["勺子", "スプーン", "すぷーん", "spoon", "word"],
      ["叉子", "フォーク", "ふぉーく", "fork", "word"],
      ["刀", "ナイフ", "ないふ", "knife", "word"],
      ["盘子", "皿", "さら", "plate", "word"],
      ["碗", "茶碗", "ちゃわん", "bowl", "word"],
      ["玻璃杯", "グラス", "ぐらす", "glass", "word"],
      ["餐巾纸", "ナプキン", "なぷきん", "napkin", "word"],
      ["结账", "お会計", "おかいけい", "bill", "word"],
      ["收银台", "レジ", "れじ", "cash register", "word"],
      ["服务员", "ウェイター", "うぇいたー", "waiter", "word"],
      ["空位", "空席", "くうせき", "vacant seat", "word"],
      ["吸烟区", "喫煙席", "きつえんせき", "smoking seat", "word"],
      ["禁烟区", "禁煙席", "きんえんせき", "non-smoking seat", "word"],
      ["外带", "持ち帰り", "もちかえり", "takeout", "word"],
      ["堂食", "店内で食べる", "てんないでたべる", "eat in", "phrase"],
      ["好吃", "おいしい", "おいしい", "delicious", "word"],
      ["难吃", "まずい", "まずい", "not tasty", "word"],
      ["甜", "甘い", "あまい", "sweet", "word"],
      ["咸", "しょっぱい", "しょっぱい", "salty", "word"],
      ["辣", "辛い", "からい", "spicy", "word"],
      ["苦", "苦い", "にがい", "bitter", "word"],
      ["酸", "酸っぱい", "すっぱい", "sour", "word"],
      ["热", "熱い", "あつい", "hot", "word"],
      ["冷", "冷たい", "つめたい", "cold", "word"],
      ["新鲜", "新鮮", "しんせん", "fresh", "word"],
      ["吃饱了", "お腹いっぱい", "おなかいっぱい", "full", "phrase"],
      ["饿了", "お腹が空いた", "おなかがすいた", "hungry", "phrase"],
      ["渴了", "喉が渇いた", "のどがかわいた", "thirsty", "phrase"],
      ["过敏", "アレルギー", "あれるぎー", "allergy", "word"],
      ["素食者", "ベジタリアン", "べじたりあん", "vegetarian", "word"],
      ["请问有中文菜单吗？", "中国語のメニューはありますか？", "ちゅうごくごのめにゅーはありますか？", "Do you have a Chinese menu?", "phrase"],
      ["请给我这个。", "これをください。", "これをください。", "Please give me this one.", "phrase"],
      ["不要辣。", "辛くしないでください。", "からくしないでください。", "Not spicy, please.", "phrase"],
      ["结账。", "お会計をお願いします。", "おかいけいをおねがいします。", "Check, please.", "phrase"],
      ["我可以点餐吗？", "注文してもいいですか？", "ちゅうもんしてもいいですか？", "Can I order?", "phrase"],
      ["我对……过敏。", "…にアレルギーがあります。", "…にあれるぎーがあります。", "I am allergic to ...", "phrase"],
      ["再来一杯水。", "水をもう一杯ください。", "みずをもういっぱいください。", "One more glass of water, please.", "phrase"],
      ["这个好吃吗？", "これはおいしいですか？", "これはおいしいですか？", "Is this delicious?", "phrase"]
    ],

    shopping: [
      ["商店", "店", "みせ", "shop", "word"],
      ["商场", "デパート", "でぱーと", "department store", "word"],
      ["超市", "スーパー", "すーぱー", "supermarket", "word"],
      ["便利店", "コンビニ", "こんびに", "convenience store", "word"],
      ["市场", "市場", "いちば", "market", "word"],
      ["价格", "値段", "ねだん", "price", "word"],
      ["多少钱", "いくら", "いくら", "how much", "word"],
      ["贵", "高い", "たかい", "expensive", "word"],
      ["便宜", "安い", "やすい", "cheap", "word"],
      ["打折", "割引", "わりびき", "discount", "word"],
      ["促销", "セール", "せーる", "sale", "word"],
      ["小票", "レシート", "れしーと", "receipt", "word"],
      ["现金", "現金", "げんきん", "cash", "word"],
      ["信用卡", "クレジットカード", "くれじっとかーど", "credit card", "word"],
      ["银行卡", "キャッシュカード", "きゃっしゅかーど", "bank card", "word"],
      ["零钱", "小銭", "こぜに", "small change", "word"],
      ["支付", "支払い", "しはらい", "payment", "word"],
      ["手机支付", "スマホ決済", "すまほけっさい", "mobile payment", "word"],
      ["二维码", "二次元コード", "にじげんこーど", "QR code", "word"],
      ["试衣间", "試着室", "しちゃくしつ", "fitting room", "word"],
      ["试穿", "試着する", "しちゃくする", "to try on", "word"],
      ["尺寸", "サイズ", "さいず", "size", "word"],
      ["大号", "Lサイズ", "えるさいず", "large", "word"],
      ["中号", "Mサイズ", "えむさいず", "medium", "word"],
      ["小号", "Sサイズ", "えすさいず", "small", "word"],
      ["衣服", "服", "ふく", "clothes", "word"],
      ["衬衫", "シャツ", "しゃつ", "shirt", "word"],
      ["T恤", "Tシャツ", "てぃーしゃつ", "T-shirt", "word"],
      ["裤子", "ズボン", "ずぼん", "pants", "word"],
      ["牛仔裤", "ジーンズ", "じーんず", "jeans", "word"],
      ["裙子", "スカート", "すかーと", "skirt", "word"],
      ["连衣裙", "ワンピース", "わんぴーす", "dress", "word"],
      ["外套", "コート", "こーと", "coat", "word"],
      ["毛衣", "セーター", "せーたー", "sweater", "word"],
      ["内衣", "下着", "したぎ", "underwear", "word"],
      ["袜子", "靴下", "くつした", "socks", "word"],
      ["鞋子", "靴", "くつ", "shoes", "word"],
      ["运动鞋", "スニーカー", "すにーかー", "sneakers", "word"],
      ["帽子", "帽子", "ぼうし", "hat", "word"],
      ["围巾", "マフラー", "まふらー", "scarf", "word"],
      ["手套", "手袋", "てぶくろ", "gloves", "word"],
      ["包", "バッグ", "ばっぐ", "bag", "word"],
      ["钱包", "財布", "さいふ", "wallet", "word"],
      ["眼镜", "眼鏡", "めがね", "glasses", "word"],
      ["太阳镜", "サングラス", "さんぐらす", "sunglasses", "word"],
      ["手表", "腕時計", "うでどけい", "watch", "word"],
      ["首饰", "アクセサリー", "あくせさりー", "accessories", "word"],
      ["化妆品", "化粧品", "けしょうひん", "cosmetics", "word"],
      ["护肤品", "スキンケア用品", "すきんけあようひん", "skincare", "word"],
      ["香水", "香水", "こうすい", "perfume", "word"],
      ["口红", "口紅", "くちべに", "lipstick", "word"],
      ["洗面奶", "洗顔料", "せんがんりょう", "facial cleanser", "word"],
      ["食品", "食品", "しょくひん", "food", "word"],
      ["饮料", "飲み物", "のみもの", "drinks", "word"],
      ["零食", "お菓子", "おかし", "snacks", "word"],
      ["纪念品", "お土産", "おみやげ", "souvenir", "word"],
      ["特产", "名物", "めいぶつ", "local specialty", "word"],
      ["玩具", "おもちゃ", "おもちゃ", "toy", "word"],
      ["电子产品", "電子機器", "でんしきき", "electronics", "word"],
      ["手机", "携帯電話", "けいたいでんわ", "mobile phone", "word"],
      ["充电器", "充電器", "じゅうでんき", "charger", "word"],
      ["耳机", "イヤホン", "いやほん", "earphones", "word"],
      ["相机", "カメラ", "かめら", "camera", "word"],
      ["电池", "電池", "でんち", "battery", "word"],
      ["购物袋", "買い物袋", "かいものぶくろ", "shopping bag", "word"],
      ["环保袋", "エコバッグ", "えこばっぐ", "eco bag", "word"],
      ["可以退税吗？", "免税できますか？", "めんぜいできますか？", "Is this tax-free?", "phrase"],
      ["可以便宜一点吗？", "安くしてもらえますか？", "やすくしてもらえますか？", "Can you make it cheaper?", "phrase"],
      ["我只是看看。", "見ているだけです。", "みているだけです。", "I'm just looking.", "phrase"],
      ["我要这个。", "これをください。", "これをください。", "I'll take this one.", "phrase"],
      ["可以刷卡吗？", "カードで払えますか？", "かーどではらえますか？", "Can I pay by card?", "phrase"],
      ["有没有大一点的？", "もっと大きいのはありますか？", "もっとおおきいのはありますか？", "Do you have a bigger one?", "phrase"],
      ["可以试穿吗？", "試着してもいいですか？", "しちゃくしてもいいですか？", "Can I try it on?", "phrase"]
    ],

    directions: [
      ["哪里", "どこ", "どこ", "where", "word"],
      ["这里", "ここ", "ここ", "here", "word"],
      ["那里", "あそこ", "あそこ", "over there", "word"],
      ["左边", "左", "ひだり", "left", "word"],
      ["右边", "右", "みぎ", "right", "word"],
      ["前面", "前", "まえ", "front", "word"],
      ["后面", "後ろ", "うしろ", "back", "word"],
      ["旁边", "隣", "となり", "next to", "word"],
      ["对面", "向かい", "むかい", "opposite", "word"],
      ["附近", "近く", "ちかく", "nearby", "word"],
      ["远", "遠い", "とおい", "far", "word"],
      ["近", "近い", "ちかい", "near", "word"],
      ["直走", "まっすぐ", "まっすぐ", "straight", "word"],
      ["转弯", "曲がる", "まがる", "to turn", "word"],
      ["十字路口", "交差点", "こうさてん", "intersection", "word"],
      ["桥", "橋", "はし", "bridge", "word"],
      ["路", "道", "みち", "road", "word"],
      ["街道", "通り", "とおり", "street", "word"],
      ["建筑", "建物", "たてもの", "building", "word"],
      ["派出所", "交番", "こうばん", "police box", "word"],
      ["医院", "病院", "びょういん", "hospital", "word"],
      ["药店", "薬局", "やっきょく", "pharmacy", "word"],
      ["银行", "銀行", "ぎんこう", "bank", "word"],
      ["邮局", "郵便局", "ゆうびんきょく", "post office", "word"],
      ["厕所", "トイレ", "といれ", "toilet", "word"],
      ["公交站", "バス停", "ばすてい", "bus stop", "word"],
      ["地铁站", "地下鉄の駅", "ちかてつのえき", "subway station", "word"],
      ["景点", "観光地", "かんこうち", "tourist spot", "word"],
      ["博物馆", "博物館", "はくぶつかん", "museum", "word"],
      ["公园", "公園", "こうえん", "park", "word"],
      ["请问怎么走？", "どうやって行きますか？", "どうやっていきますか？", "How do I get there?", "phrase"],
      ["……在哪里？", "…はどこですか？", "…はどこですか？", "Where is ...?", "phrase"],
      ["请带我去……", "…まで連れて行ってください。", "…までつれていってください。", "Please take me to ...", "phrase"],
      ["我要去……", "…に行きたいです。", "…にいきたいです。", "I want to go to ...", "phrase"],
      ["走路要几分钟？", "歩いて何分ですか？", "あるいてなんぷんですか？", "How many minutes on foot?", "phrase"],
      ["坐地铁能到吗？", "地下鉄で行けますか？", "ちかてつでいけますか？", "Can I get there by subway?", "phrase"],
      ["我迷路了。", "道に迷いました。", "みちにまよいました。", "I'm lost.", "phrase"],
      ["请问现在在哪里？", "今どこにいますか？", "いまどこにいますか？", "Where am I now?", "phrase"],
      ["请在地图上指给我。", "地図で指してください。", "ちずでさしてください。", "Please point on the map.", "phrase"],
      ["能再说一遍吗？", "もう一度言ってください。", "もういちどいってください。", "Could you say it again?", "phrase"],
      ["怎么去车站？", "駅までどうやって行きますか？", "えきまでどうやっていきますか？", "How do I get to the station?", "phrase"],
      ["这是哪条路？", "この道は何という道ですか？", "このみちはなんというみちですか？", "What street is this?", "phrase"],
      ["洗手间在哪里？", "お手洗いはどこですか？", "おてあらいはどこですか？", "Where is the restroom?", "phrase"]
    ],

    numbers: [
      ["零", "ゼロ", "ぜろ", "zero", "word"],
      ["一", "一", "いち", "one", "word"],
      ["二", "二", "に", "two", "word"],
      ["三", "三", "さん", "three", "word"],
      ["四", "四", "よん", "four", "word"],
      ["五", "五", "ご", "five", "word"],
      ["六", "六", "ろく", "six", "word"],
      ["七", "七", "なな", "seven", "word"],
      ["八", "八", "はち", "eight", "word"],
      ["九", "九", "きゅう", "nine", "word"],
      ["十", "十", "じゅう", "ten", "word"],
      ["百", "百", "ひゃく", "hundred", "word"],
      ["千", "千", "せん", "thousand", "word"],
      ["万", "万", "まん", "ten thousand", "word"],
      ["日元", "円", "えん", "yen", "word"],
      ["美元", "ドル", "どる", "dollar", "word"],
      ["人民币", "人民元", "じんみんげん", "yuan", "word"],
      ["今天", "今日", "きょう", "today", "word"],
      ["明天", "明日", "あした", "tomorrow", "word"],
      ["昨天", "昨日", "きのう", "yesterday", "word"],
      ["后天", "明後日", "あさって", "day after tomorrow", "word"],
      ["前天", "一昨日", "おととい", "day before yesterday", "word"],
      ["早上", "朝", "あさ", "morning", "word"],
      ["中午", "昼", "ひる", "noon", "word"],
      ["下午", "午後", "ごご", "afternoon", "word"],
      ["晚上", "夜", "よる", "night", "word"],
      ["现在", "今", "いま", "now", "word"],
      ["时间", "時間", "じかん", "time", "word"],
      ["一小时", "一時間", "いちじかん", "one hour", "word"],
      ["一分钟", "一分", "いっぷん", "one minute", "word"],
      ["秒", "秒", "びょう", "second", "word"],
      ["几点", "何時", "なんじ", "what time", "word"],
      ["星期", "曜日", "ようび", "day of the week", "word"],
      ["星期一", "月曜日", "げつようび", "Monday", "word"],
      ["星期二", "火曜日", "かようび", "Tuesday", "word"],
      ["星期三", "水曜日", "すいようび", "Wednesday", "word"],
      ["星期四", "木曜日", "もくようび", "Thursday", "word"],
      ["星期五", "金曜日", "きんようび", "Friday", "word"],
      ["星期六", "土曜日", "どようび", "Saturday", "word"],
      ["星期日", "日曜日", "にちようび", "Sunday", "word"],
      ["周末", "週末", "しゅうまつ", "weekend", "word"],
      ["工作日", "平日", "へいじつ", "weekday", "word"],
      ["日期", "日付", "ひづけ", "date", "word"],
      ["一月", "一月", "いちがつ", "January", "word"],
      ["二月", "二月", "にがつ", "February", "word"],
      ["三月", "三月", "さんがつ", "March", "word"],
      ["四月", "四月", "しがつ", "April", "word"],
      ["五月", "五月", "ごがつ", "May", "word"],
      ["六月", "六月", "ろくがつ", "June", "word"],
      ["七月", "七月", "しちがつ", "July", "word"],
      ["八月", "八月", "はちがつ", "August", "word"],
      ["九月", "九月", "くがつ", "September", "word"],
      ["十月", "十月", "じゅうがつ", "October", "word"],
      ["十一月", "十一月", "じゅういちがつ", "November", "word"],
      ["十二月", "十二月", "じゅうにがつ", "December", "word"],
      ["一日", "一日", "ついたち", "1st", "word"],
      ["二日", "二日", "ふつか", "2nd", "word"],
      ["三日", "三日", "みっか", "3rd", "word"],
      ["四日", "四日", "よっか", "4th", "word"],
      ["五日", "五日", "いつか", "5th", "word"],
      ["六日", "六日", "むいか", "6th", "word"],
      ["七日", "七日", "なのか", "7th", "word"],
      ["八日", "八日", "ようか", "8th", "word"],
      ["九日", "九日", "ここのか", "9th", "word"],
      ["十日", "十日", "とおか", "10th", "word"],
      ["今年", "今年", "ことし", "this year", "word"],
      ["去年", "去年", "きょねん", "last year", "word"],
      ["明年", "来年", "らいねん", "next year", "word"],
      ["这个月", "今月", "こんげつ", "this month", "word"],
      ["上个月", "先月", "せんげつ", "last month", "word"],
      ["下个月", "来月", "らいげつ", "next month", "word"],
      ["几点开门？", "何時に開きますか？", "なんじにあきますか？", "What time does it open?", "phrase"],
      ["现在几点？", "今何時ですか？", "いまなんじですか？", "What time is it now?", "phrase"],
      ["今天星期几？", "今日は何曜日ですか？", "きょうはなんようびですか？", "What day is it today?", "phrase"],
      ["今天是几号？", "今日は何日ですか？", "きょうはなんにちですか？", "What date is it today?", "phrase"],
      ["营业时间", "営業時間", "えいぎょうじかん", "business hours", "word"],
      ["开门", "開く", "ひらく", "to open", "word"],
      ["关门", "閉まる", "しまる", "to close", "word"],
      ["每天", "毎日", "まいにち", "every day", "word"],
      ["有时", "時々", "ときどき", "sometimes", "word"],
      ["经常", "よく", "よく", "often", "word"],
      ["马上", "すぐ", "すぐ", "soon", "word"],
      ["稍等", "ちょっと待って", "ちょっとまって", "wait a moment", "phrase"]
    ],

    emergency: [
      ["救命", "助けて", "たすけて", "help", "word"],
      ["紧急", "緊急", "きんきゅう", "emergency", "word"],
      ["报警", "警察を呼ぶ", "けいさつをよぶ", "call the police", "word"],
      ["叫救护车", "救急車を呼ぶ", "きゅうきゅうしゃをよぶ", "call an ambulance", "word"],
      ["医生", "医者", "いしゃ", "doctor", "word"],
      ["护士", "看護師", "かんごし", "nurse", "word"],
      ["药", "薬", "くすり", "medicine", "word"],
      ["处方", "処方箋", "しょほうせん", "prescription", "word"],
      ["发烧", "熱", "ねつ", "fever", "word"],
      ["感冒", "風邪", "かぜ", "cold", "word"],
      ["咳嗽", "咳", "せき", "cough", "word"],
      ["头疼", "頭痛", "ずつう", "headache", "word"],
      ["肚子疼", "腹痛", "ふくつう", "stomachache", "word"],
      ["牙疼", "歯痛", "しつう", "toothache", "word"],
      ["恶心", "吐き気", "はきけ", "nausea", "word"],
      ["呕吐", "嘔吐", "おうと", "vomiting", "word"],
      ["腹泻", "下痢", "げり", "diarrhea", "word"],
      ["便秘", "便秘", "べんぴ", "constipation", "word"],
      ["受伤", "怪我", "けが", "injury", "word"],
      ["流血", "出血", "しゅっけつ", "bleeding", "word"],
      ["骨折", "骨折", "こっせつ", "fracture", "word"],
      ["烫伤", "火傷", "やけど", "burn", "word"],
      ["哮喘", "喘息", "ぜんそく", "asthma", "word"],
      ["药片", "錠剤", "じょうざい", "tablet", "word"],
      ["药膏", "軟膏", "なんこう", "ointment", "word"],
      ["创可贴", "絆創膏", "ばんそうこう", "band-aid", "word"],
      ["绷带", "包帯", "ほうたい", "bandage", "word"],
      ["体温计", "体温計", "たいおんけい", "thermometer", "word"],
      ["口罩", "マスク", "ますく", "mask", "word"],
      ["消毒液", "消毒液", "しょうどくえき", "disinfectant", "word"],
      ["急救箱", "救急箱", "きゅうきゅうばこ", "first aid kit", "word"],
      ["保险", "保険", "ほけん", "insurance", "word"],
      ["保险卡", "保険証", "ほけんしょう", "insurance card", "word"],
      ["我把护照弄丢了。", "パスポートをなくしました。", "ぱすぽーとをなくしました。", "I lost my passport.", "phrase"],
      ["我的钱包被偷了。", "財布を盗まれました。", "さいふをぬすまれました。", "My wallet was stolen.", "phrase"],
      ["我需要帮助。", "助けてください。", "たすけてください。", "I need help.", "phrase"],
      ["请叫警察。", "警察を呼んでください。", "けいさつをよんでください。", "Please call the police.", "phrase"],
      ["请叫救护车。", "救急車を呼んでください。", "きゅうきゅうしゃをよんでください。", "Please call an ambulance.", "phrase"],
      ["我不舒服。", "気分が悪いです。", "きぶんがわるいです。", "I feel sick.", "phrase"],
      ["我生病了。", "病気です。", "びょうきです。", "I am ill.", "phrase"],
      ["我对……过敏。", "…にアレルギーがあります。", "…にあれるぎーがあります。", "I am allergic to ...", "phrase"],
      ["哪里有药店？", "薬局はどこですか？", "やっきょくはどこですか？", "Where is a pharmacy?", "phrase"],
      ["我需要看医生。", "医者に診てもらいたいです。", "いしゃにみてもらいたいです。", "I need to see a doctor.", "phrase"],
      ["这很紧急。", "緊急です。", "きんきゅうです。", "This is an emergency.", "phrase"]
    ],

    expressions: [
      ["谢谢", "ありがとう", "ありがとう", "thank you", "word"],
      ["非常感谢", "ありがとうございます", "ありがとうございます", "thank you very much", "word"],
      ["不客气", "どういたしまして", "どういたしまして", "you're welcome", "word"],
      ["请", "ください", "ください", "please", "word"],
      ["对不起", "すみません", "すみません", "excuse me / sorry", "word"],
      ["抱歉", "ごめんなさい", "ごめんなさい", "I'm sorry", "word"],
      ["你好", "こんにちは", "こんにちは", "hello", "word"],
      ["早上好", "おはようございます", "おはようございます", "good morning", "word"],
      ["晚上好", "こんばんは", "こんばんは", "good evening", "word"],
      ["再见", "さようなら", "さようなら", "goodbye", "word"],
      ["回头见", "またね", "またね", "see you later", "word"],
      ["晚安", "おやすみなさい", "おやすみなさい", "good night", "word"],
      ["欢迎光临", "いらっしゃいませ", "いらっしゃいませ", "welcome", "word"],
      ["我明白了", "わかりました", "わかりました", "I understand", "phrase"],
      ["我不明白", "わかりません", "わかりません", "I don't understand", "phrase"],
      ["是的", "はい", "はい", "yes", "word"],
      ["不是", "いいえ", "いいえ", "no", "word"],
      ["可以", "大丈夫", "だいじょうぶ", "okay", "word"],
      ["没关系", "大丈夫です", "だいじょうぶです", "it's okay", "phrase"],
      ["没问题", "構いません", "かまいません", "no problem", "phrase"],
      ["好的", "オーケー", "おーけー", "OK", "word"],
      ["我喜欢", "好きです", "すきです", "I like it", "phrase"],
      ["我不喜欢", "好きじゃありません", "すきじゃありません", "I don't like it", "phrase"],
      ["想要", "ほしい", "ほしい", "want", "word"],
      ["需要", "必要", "ひつよう", "need", "word"],
      ["有", "あります", "あります", "there is / have", "word"],
      ["没有", "ありません", "ありません", "there isn't / don't have", "word"],
      ["是", "です", "です", "is", "word"],
      ["不是", "じゃありません", "じゃありません", "is not", "phrase"],
      ["我叫……", "…と申します", "…ともうします", "my name is ...", "phrase"],
      ["你叫什么名字？", "お名前は何ですか？", "おなまえはなんですか？", "What is your name?", "phrase"],
      ["我是中国人。", "私は中国人です。", "わたしはちゅうごくじんです。", "I am Chinese.", "phrase"],
      ["你会说英语吗？", "英語を話せますか？", "えいごをはなせますか？", "Can you speak English?", "phrase"],
      ["请说慢一点。", "ゆっくり話してください。", "ゆっくりはなしてください。", "Please speak slowly.", "phrase"],
      ["请再说一遍。", "もう一度言ってください。", "もういちどいってください。", "Please say it again.", "phrase"],
      ["什么意思？", "どういう意味ですか？", "どういういみですか？", "What does it mean?", "phrase"],
      ["怎么读？", "どう読みますか？", "どうよみますか？", "How do you read it?", "phrase"],
      ["怎么写？", "どう書きますか？", "どうかきますか？", "How do you write it?", "phrase"],
      ["多少钱？", "いくらですか？", "いくらですか？", "How much is it?", "phrase"],
      ["在哪里？", "どこですか？", "どこですか？", "Where is it?", "phrase"],
      ["什么时候？", "いつですか？", "いつですか？", "When is it?", "phrase"],
      ["为什么？", "なぜですか？", "なぜですか？", "Why?", "phrase"],
      ["怎么办？", "どうすればいいですか？", "どうすればいいですか？", "What should I do?", "phrase"],
      ["可以吗？", "いいですか？", "いいですか？", "Is it okay?", "phrase"],
      ["可以。", "いいですよ。", "いいですよ。", "It's fine.", "phrase"],
      ["不行。", "だめです。", "だめです。", "No / not allowed.", "phrase"],
      ["有中文吗？", "中国語はありますか？", "ちゅうごくごはありますか？", "Do you have Chinese?", "phrase"]
    ]
  };

  const entries = [];
  Object.keys(groups).forEach((category) => {
    groups[category].forEach((item, index) => {
      const [zh, ja, reading, en, type] = item;
      entries.push({
        id: `${category}_${String(index + 1).padStart(3, "0")}`,
        category,
        zh,
        ja,
        reading,
        en,
        type
      });
    });
  });

  return entries;
})();
