window.CATEGORIES = [
  { id: "airport", name: "机场与交通", icon: "✈️" },
  { id: "hotel", name: "住宿", icon: "🏨" },
  { id: "food", name: "餐饮", icon: "🍜" },
  { id: "shopping", name: "购物", icon: "🛍️" },
  { id: "directions", name: "问路与方向", icon: "🧭" },
  { id: "numbers", name: "数字、时间与日期", icon: "🕐" },
  { id: "emergency", name: "紧急与健康", icon: "🆘" },
  { id: "expressions", name: "常用表达与礼貌用语", icon: "💬" }
];

window.WORD_BANK = (function () {
  const groups = {
    airport: [
      ["airport_001", "护照", "パスポート", "ぱすぽーと", "passport", "word"],
      ["airport_002", "签证", "ビザ", "びざ", "visa", "word"],
      ["airport_003", "机票", "航空券", "こうくうけん", "airline ticket", "word"],
      ["airport_004", "登机牌", "搭乗券", "とうじょうけん", "boarding pass", "word"],
      ["airport_005", "行李", "荷物", "にもつ", "luggage", "word"],
      ["airport_006", "行李箱", "スーツケース", "すーつけーす", "suitcase", "word"],
      ["airport_007", "手提行李", "機内持ち込み手荷物", "きないもちこみてにもつ", "carry-on baggage", "word"],
      ["airport_008", "机场", "空港", "くうこう", "airport", "word"],
      ["airport_009", "航站楼", "ターミナル", "たーみなる", "terminal", "word"],
      ["airport_010", "出发", "出発", "しゅっぱつ", "departure", "word"],
      ["airport_011", "到达", "到着", "とうちゃく", "arrival", "word"],
      ["airport_012", "登机口", "搭乗口", "とうじょうぐち", "boarding gate", "word"],
      ["airport_013", "安检", "保安検査", "ほあんけんさ", "security check", "word"],
      ["airport_014", "海关", "税関", "ぜいかん", "customs", "word"],
      ["airport_015", "入境", "入国", "にゅうこく", "entry", "word"],
      ["airport_016", "出境", "出国", "しゅっこく", "departure from the country", "word"],
      ["airport_017", "转机", "乗り継ぎ", "のりつぎ", "transfer", "word"],
      ["airport_018", "航班", "便", "びん", "flight", "word"],
      ["airport_019", "延误", "遅延", "ちえん", "delay", "word"],
      ["airport_020", "取消", "キャンセル", "きゃんせる", "cancellation", "word"],
      ["airport_021", "值机", "チェックイン", "ちぇっくいん", "check-in", "word"],
      ["airport_022", "登机", "搭乗", "とうじょう", "boarding", "word"],
      ["airport_023", "起飞", "離陸", "りりく", "takeoff", "word"],
      ["airport_024", "降落", "着陸", "ちゃくりく", "landing", "word"],
      ["airport_025", "座位", "座席", "ざせき", "seat", "word"],
      ["airport_026", "靠窗座位", "窓側の席", "まどがわのせき", "window seat", "word"],
      ["airport_027", "过道座位", "通路側の席", "つうろがわのせき", "aisle seat", "word"],
      ["airport_028", "行李领取处", "手荷物受取所", "てにもつうけとりじょ", "baggage claim", "word"],
      ["airport_029", "行李推车", "カート", "かーと", "luggage cart", "word"],
      ["airport_030", "护照查验", "パスポートコントロール", "ぱすぽーとこんとろーる", "passport control", "word"],
      ["airport_031", "免税店", "免税店", "めんぜいてん", "duty-free shop", "word"],
      ["airport_032", "机场大巴", "空港バス", "くうこうばす", "airport bus", "word"],
      ["airport_033", "出租车", "タクシー", "たくしー", "taxi", "word"],
      ["airport_034", "地铁", "地下鉄", "ちかてつ", "subway", "word"],
      ["airport_035", "火车", "電車", "でんしゃ", "train", "word"],
      ["airport_036", "高铁", "新幹線", "しんかんせん", "bullet train", "word"],
      ["airport_037", "公交车", "バス", "ばす", "bus", "word"],
      ["airport_038", "车站", "駅", "えき", "station", "word"],
      ["airport_039", "站台", "ホーム", "ほーむ", "platform", "word"],
      ["airport_040", "时刻表", "時刻表", "じこくひょう", "timetable", "word"],
      ["airport_041", "单程票", "片道切符", "かたみちきっぷ", "one-way ticket", "word"],
      ["airport_042", "往返票", "往復切符", "おうふくきっぷ", "round-trip ticket", "word"],
      ["airport_043", "车票", "切符", "きっぷ", "ticket", "word"],
      ["airport_044", "售票处", "切符売り場", "きっぷうりば", "ticket office", "word"],
      ["airport_045", "自动售票机", "自動券売機", "じどうけんばいき", "ticket machine", "word"],
      ["airport_046", "检票口", "改札口", "かいさつぐち", "ticket gate", "word"],
      ["airport_047", "入口", "入口", "いりぐち", "entrance", "word"],
      ["airport_048", "出口", "出口", "でぐち", "exit", "word"],
      ["airport_049", "问讯处", "案内所", "あんないじょ", "information desk", "word"],
      ["airport_050", "地图", "地図", "ちず", "map", "word"],
      ["airport_051", "目的地", "目的地", "もくてきち", "destination", "word"],
      ["airport_052", "汽车", "車", "くるま", "car", "word"],
      ["airport_053", "租车", "レンタカー", "れんたかー", "rental car", "word"],
      ["airport_054", "加油站", "ガソリンスタンド", "がそりんすたんど", "gas station", "word"],
      ["airport_055", "停车场", "駐車場", "ちゅうしゃじょう", "parking lot", "word"],
      ["airport_056", "红绿灯", "信号", "しんごう", "traffic light", "word"],
      ["airport_057", "人行横道", "横断歩道", "おうだんほどう", "crosswalk", "word"],
      ["airport_058", "自行车", "自転車", "じてんしゃ", "bicycle", "word"],
      ["airport_059", "摩托车", "バイク", "ばいく", "motorcycle", "word"],
      ["airport_060", "步行", "徒歩", "とほ", "on foot", "word"],
      ["airport_061", "直飞", "直行便", "ちょっこうびん", "direct flight", "word"],
      ["airport_062", "行李寄存", "荷物預かり", "にもつあずかり", "luggage storage", "word"],
      ["airport_063", "行李丢失", "荷物紛失", "にもつふんしつ", "lost luggage", "word"],
      ["airport_064", "护照号码", "パスポート番号", "ぱすぽーとばんごう", "passport number", "word"],
      ["airport_065", "航班号", "便名", "びんめい", "flight number", "word"],
      ["airport_066", "候机室", "待合室", "まちあいしつ", "waiting room", "word"],
      ["airport_067", "登机时间", "搭乗時刻", "とうじょうじこく", "boarding time", "word"],
      ["airport_068", "随身携带", "持ち込む", "もちこむ", "to carry on", "word"],
      ["airport_069", "托运", "預ける", "あずける", "to check in luggage", "word"],
      ["airport_070", "行李检查", "手荷物検査", "てにもつけんさ", "baggage inspection", "word"],
      ["airport_071", "入境卡", "入国カード", "にゅうこくかーど", "arrival card", "word"],
      ["airport_072", "海关申报", "税関申告", "ぜいかんしんこく", "customs declaration", "word"],
      ["airport_073", "转机柜台", "乗り継ぎカウンター", "のりつぎかうんたー", "transfer counter", "word"],
      ["airport_074", "安全带", "シートベルト", "しーとべると", "seat belt", "word"],
      ["airport_075", "空乘", "客室乗務員", "きゃくしつじょうむいん", "flight attendant", "word"],
      ["airport_076", "机长", "機長", "きちょう", "captain", "word"],
      ["airport_077", "登机桥", "搭乗橋", "とうじょうきょう", "jet bridge", "word"],
      ["airport_078", "跑道", "滑走路", "かっそうろ", "runway", "word"],
      ["airport_079", "签证延期", "ビザ延長", "びざえんちょう", "visa extension", "word"],
      ["airport_080", "入境检查", "入国審査", "にゅうこくしんさ", "immigration inspection", "word"],
      ["airport_081", "行李超重", "超過手荷物", "ちょうかてにもつ", "excess baggage", "word"],
      ["airport_082", "靠窗", "窓側", "まどがわ", "window side", "word"],
      ["airport_083", "靠过道", "通路側", "つうろがわ", "aisle side", "word"],
      ["airport_084", "救生衣", "救命胴衣", "きゅうめいどうい", "life jacket", "word"],
      ["airport_085", "请问在哪里登机？", "搭乗口はどこですか？", "とうじょうぐちはどこですか？", "Where is the boarding gate?", "phrase"],
      ["airport_086", "请问在哪里取行李？", "荷物はどこで受け取りますか？", "にもつはどこでうけとりますか？", "Where can I pick up my luggage?", "phrase"],
      ["airport_087", "我想换乘。", "乗り換えたいです。", "のりかえたいです。", "I want to transfer.", "phrase"]
    ],

    hotel: [
      ["hotel_001", "酒店", "ホテル", "ほてる", "hotel", "word"],
      ["hotel_002", "日式旅馆", "旅館", "りょかん", "Japanese inn", "word"],
      ["hotel_003", "民宿", "民宿", "みんしゅく", "guesthouse", "word"],
      ["hotel_004", "前台", "フロント", "ふろんと", "front desk", "word"],
      ["hotel_005", "预订", "予約", "よやく", "reservation", "word"],
      ["hotel_006", "入住", "チェックイン", "ちぇっくいん", "check-in", "word"],
      ["hotel_007", "退房", "チェックアウト", "ちぇっくあうと", "check-out", "word"],
      ["hotel_008", "房间", "部屋", "へや", "room", "word"],
      ["hotel_009", "单人房", "シングルルーム", "しんぐるるーむ", "single room", "word"],
      ["hotel_010", "双人房", "ツインルーム", "ついんるーむ", "twin room", "word"],
      ["hotel_011", "大床房", "ダブルルーム", "だぶるるーむ", "double room", "word"],
      ["hotel_012", "套房", "スイートルーム", "すいーとるーむ", "suite", "word"],
      ["hotel_013", "钥匙", "鍵", "かぎ", "key", "word"],
      ["hotel_014", "房卡", "ルームキー", "るーむきー", "room key", "word"],
      ["hotel_015", "行李员", "ベルボーイ", "べるぼーい", "bellboy", "word"],
      ["hotel_016", "工作人员", "スタッフ", "すたっふ", "staff", "word"],
      ["hotel_017", "客房服务", "ルームサービス", "るーむさーびす", "room service", "word"],
      ["hotel_018", "打扫", "掃除", "そうじ", "cleaning", "word"],
      ["hotel_019", "毛巾", "タオル", "たおる", "towel", "word"],
      ["hotel_020", "床单", "シーツ", "しーつ", "bed sheet", "word"],
      ["hotel_021", "枕头", "枕", "まくら", "pillow", "word"],
      ["hotel_022", "被子", "布団", "ふとん", "futon / duvet", "word"],
      ["hotel_023", "毯子", "毛布", "もうふ", "blanket", "word"],
      ["hotel_024", "空调", "エアコン", "えあこん", "air conditioner", "word"],
      ["hotel_025", "暖气", "暖房", "だんぼう", "heating", "word"],
      ["hotel_026", "浴室", "浴室", "よくしつ", "bathroom", "word"],
      ["hotel_027", "淋浴", "シャワー", "しゃわー", "shower", "word"],
      ["hotel_028", "浴缸", "バスタブ", "ばすたぶ", "bathtub", "word"],
      ["hotel_029", "热水", "お湯", "おゆ", "hot water", "word"],
      ["hotel_030", "冷水", "冷水", "れいすい", "cold water", "word"],
      ["hotel_031", "卫生间", "トイレ", "といれ", "toilet", "word"],
      ["hotel_032", "卫生纸", "トイレットペーパー", "といれっとぺーぱー", "toilet paper", "word"],
      ["hotel_033", "洗发水", "シャンプー", "しゃんぷー", "shampoo", "word"],
      ["hotel_034", "沐浴露", "ボディソープ", "ぼでぃそーぷ", "body soap", "word"],
      ["hotel_035", "牙刷", "歯ブラシ", "はぶらし", "toothbrush", "word"],
      ["hotel_036", "牙膏", "歯磨き粉", "はみがきこ", "toothpaste", "word"],
      ["hotel_037", "吹风机", "ドライヤー", "どらいやー", "hair dryer", "word"],
      ["hotel_038", "插座", "コンセント", "こんせんと", "outlet", "word"],
      ["hotel_039", "转换插头", "変換プラグ", "へんかんぷらぐ", "plug adapter", "word"],
      ["hotel_040", "无线网络", "Wi-Fi", "わいふぁい", "Wi-Fi", "word"],
      ["hotel_041", "网络", "インターネット", "いんたーねっと", "internet", "word"],
      ["hotel_042", "电梯", "エレベーター", "えれべーたー", "elevator", "word"],
      ["hotel_043", "楼梯", "階段", "かいだん", "stairs", "word"],
      ["hotel_044", "大堂", "ロビー", "ろびー", "lobby", "word"],
      ["hotel_045", "餐厅", "レストラン", "れすとらん", "restaurant", "word"],
      ["hotel_046", "早餐", "朝食", "ちょうしょく", "breakfast", "word"],
      ["hotel_047", "叫醒服务", "モーニングコール", "もーにんぐこーる", "wake-up call", "word"],
      ["hotel_048", "洗衣服务", "ランドリーサービス", "らんどりーさーびす", "laundry service", "word"],
      ["hotel_049", "熨斗", "アイロン", "あいろん", "iron", "word"],
      ["hotel_050", "保险箱", "セーフティボックス", "せーふてぃぼっくす", "safe box", "word"],
      ["hotel_051", "退房时间", "チェックアウト時間", "ちぇっくあうとじかん", "check-out time", "word"],
      ["hotel_052", "入住时间", "チェックイン時間", "ちぇっくいんじかん", "check-in time", "word"],
      ["hotel_053", "空房", "空室", "くうしつ", "vacant room", "word"],
      ["hotel_054", "满房", "満室", "まんしつ", "fully booked", "word"],
      ["hotel_055", "押金", "デポジット", "でぽじっと", "deposit", "word"],
      ["hotel_056", "收据", "領収書", "りょうしゅうしょ", "receipt", "word"],
      ["hotel_057", "账单", "請求書", "せいきゅうしょ", "bill", "word"],
      ["hotel_058", "前台电话", "フロント電話", "ふろんとでんわ", "front desk phone", "word"],
      ["hotel_059", "烟雾报警器", "火災報知器", "かさいほうちき", "smoke alarm", "word"],
      ["hotel_060", "灭火器", "消火器", "しょうかき", "fire extinguisher", "word"],
      ["hotel_061", "婴儿床", "ベビーベッド", "べびーべっど", "baby bed", "word"],
      ["hotel_062", "加床", "エキストラベッド", "えきすとらべっど", "extra bed", "word"],
      ["hotel_063", "床垫", "マットレス", "まっとれす", "mattress", "word"],
      ["hotel_064", "冰箱", "冷蔵庫", "れいぞうこ", "refrigerator", "word"],
      ["hotel_065", "微波炉", "電子レンジ", "でんしれんじ", "microwave", "word"],
      ["hotel_066", "水壶", "ポット", "ぽっと", "kettle", "word"],
      ["hotel_067", "杯子", "コップ", "こっぷ", "cup", "word"],
      ["hotel_068", "拖鞋", "スリッパ", "すりっぱ", "slippers", "word"],
      ["hotel_069", "衣架", "ハンガー", "はんがー", "hanger", "word"],
      ["hotel_070", "衣柜", "クローゼット", "くろーぜっと", "closet", "word"],
      ["hotel_071", "窗帘", "カーテン", "かーてん", "curtain", "word"],
      ["hotel_072", "阳台", "バルコニー", "ばるこにー", "balcony", "word"],
      ["hotel_073", "景色", "景色", "けしき", "view", "word"],
      ["hotel_074", "安静", "静か", "しずか", "quiet", "word"],
      ["hotel_075", "吵闹", "うるさい", "うるさい", "noisy", "word"],
      ["hotel_076", "舒适", "快適", "かいてき", "comfortable", "word"],
      ["hotel_077", "房间号", "部屋番号", "へやばんごう", "room number", "word"],
      ["hotel_078", "续住", "延泊", "えんぱく", "extend stay", "word"],
      ["hotel_079", "我把钥匙弄丢了。", "鍵をなくしました。", "かぎをなくしました。", "I lost my key.", "phrase"],
      ["hotel_080", "可以寄存行李吗？", "荷物を預かってもらえますか？", "にもつをあずかってもらえますか？", "Can I leave my luggage?", "phrase"],
      ["hotel_081", "请问几点退房？", "チェックアウトは何時ですか？", "ちぇっくあうとはなんじですか？", "What time is checkout?", "phrase"],
      ["hotel_082", "可以换个房间吗？", "部屋を変えてもらえますか？", "へやをかえてもらえますか？", "Can I change rooms?", "phrase"]
    ],

    food: [
      ["food_001", "早餐", "朝食", "ちょうしょく", "breakfast", "word"],
      ["food_002", "午餐", "昼食", "ちゅうしょく", "lunch", "word"],
      ["food_003", "晚餐", "夕食", "ゆうしょく", "dinner", "word"],
      ["food_004", "菜单", "メニュー", "めにゅー", "menu", "word"],
      ["food_005", "点菜", "注文", "ちゅうもん", "order", "word"],
      ["food_006", "水", "水", "みず", "water", "word"],
      ["food_007", "热水", "お湯", "おゆ", "hot water", "word"],
      ["food_008", "茶", "お茶", "おちゃ", "tea", "word"],
      ["food_009", "咖啡", "コーヒー", "こーひー", "coffee", "word"],
      ["food_010", "牛奶", "牛乳", "ぎゅうにゅう", "milk", "word"],
      ["food_011", "果汁", "ジュース", "じゅーす", "juice", "word"],
      ["food_012", "啤酒", "ビール", "びーる", "beer", "word"],
      ["food_013", "红酒", "ワイン", "わいん", "wine", "word"],
      ["food_014", "米饭", "ご飯", "ごはん", "rice", "word"],
      ["food_015", "面包", "パン", "ぱん", "bread", "word"],
      ["food_016", "面条", "麺", "めん", "noodles", "word"],
      ["food_017", "拉面", "ラーメン", "らーめん", "ramen", "word"],
      ["food_018", "乌冬面", "うどん", "うどん", "udon", "word"],
      ["food_019", "荞麦面", "そば", "そば", "soba", "word"],
      ["food_020", "寿司", "寿司", "すし", "sushi", "word"],
      ["food_021", "生鱼片", "刺身", "さしみ", "sashimi", "word"],
      ["food_022", "天妇罗", "天ぷら", "てんぷら", "tempura", "word"],
      ["food_023", "味噌汤", "味噌汁", "みそしる", "miso soup", "word"],
      ["food_024", "鸡蛋", "卵", "たまご", "egg", "word"],
      ["food_025", "肉", "肉", "にく", "meat", "word"],
      ["food_026", "牛肉", "牛肉", "ぎゅうにく", "beef", "word"],
      ["food_027", "猪肉", "豚肉", "ぶたにく", "pork", "word"],
      ["food_028", "鸡肉", "鶏肉", "とりにく", "chicken", "word"],
      ["food_029", "鱼", "魚", "さかな", "fish", "word"],
      ["food_030", "虾", "海老", "えび", "shrimp", "word"],
      ["food_031", "螃蟹", "蟹", "かに", "crab", "word"],
      ["food_032", "蔬菜", "野菜", "やさい", "vegetables", "word"],
      ["food_033", "水果", "果物", "くだもの", "fruit", "word"],
      ["food_034", "苹果", "りんご", "りんご", "apple", "word"],
      ["food_035", "香蕉", "バナナ", "ばなな", "banana", "word"],
      ["food_036", "橙子", "オレンジ", "おれんじ", "orange", "word"],
      ["food_037", "草莓", "いちご", "いちご", "strawberry", "word"],
      ["food_038", "西瓜", "スイカ", "すいか", "watermelon", "word"],
      ["food_039", "沙拉", "サラダ", "さらだ", "salad", "word"],
      ["food_040", "汤", "スープ", "すーぷ", "soup", "word"],
      ["food_041", "汉堡", "ハンバーガー", "はんばーがー", "hamburger", "word"],
      ["food_042", "炸鸡", "フライドチキン", "ふらいどちきん", "fried chicken", "word"],
      ["food_043", "薯条", "フライドポテト", "ふらいどぽてと", "french fries", "word"],
      ["food_044", "披萨", "ピザ", "ぴざ", "pizza", "word"],
      ["food_045", "三明治", "サンドイッチ", "さんどいっち", "sandwich", "word"],
      ["food_046", "冰淇淋", "アイスクリーム", "あいすくりーむ", "ice cream", "word"],
      ["food_047", "蛋糕", "ケーキ", "けーき", "cake", "word"],
      ["food_048", "甜点", "デザート", "でざーと", "dessert", "word"],
      ["food_049", "巧克力", "チョコレート", "ちょこれーと", "chocolate", "word"],
      ["food_050", "糖果", "キャンディー", "きゃんでぃー", "candy", "word"],
      ["food_051", "盐", "塩", "しお", "salt", "word"],
      ["food_052", "糖", "砂糖", "さとう", "sugar", "word"],
      ["food_053", "酱油", "醤油", "しょうゆ", "soy sauce", "word"],
      ["food_054", "醋", "酢", "す", "vinegar", "word"],
      ["food_055", "胡椒", "胡椒", "こしょう", "pepper", "word"],
      ["food_056", "辣椒", "唐辛子", "とうがらし", "chili", "word"],
      ["food_057", "芥末", "わさび", "わさび", "wasabi", "word"],
      ["food_058", "筷子", "箸", "はし", "chopsticks", "word"],
      ["food_059", "勺子", "スプーン", "すぷーん", "spoon", "word"],
      ["food_060", "叉子", "フォーク", "ふぉーく", "fork", "word"],
      ["food_061", "刀", "ナイフ", "ないふ", "knife", "word"],
      ["food_062", "盘子", "皿", "さら", "plate", "word"],
      ["food_063", "碗", "茶碗", "ちゃわん", "bowl", "word"],
      ["food_064", "玻璃杯", "グラス", "ぐらす", "glass", "word"],
      ["food_065", "餐巾纸", "ナプキン", "なぷきん", "napkin", "word"],
      ["food_066", "结账", "お会計", "おかいけい", "bill", "word"],
      ["food_067", "收银台", "レジ", "れじ", "cash register", "word"],
      ["food_068", "服务员", "ウェイター", "うぇいたー", "waiter", "word"],
      ["food_069", "空位", "空席", "くうせき", "vacant seat", "word"],
      ["food_070", "吸烟区", "喫煙席", "きつえんせき", "smoking seat", "word"],
      ["food_071", "禁烟区", "禁煙席", "きんえんせき", "non-smoking seat", "word"],
      ["food_072", "外带", "持ち帰り", "もちかえり", "takeout", "word"],
      ["food_073", "堂食", "店内で食べる", "てんないでたべる", "eat in", "phrase"],
      ["food_074", "好吃", "おいしい", "おいしい", "delicious", "word"],
      ["food_075", "难吃", "まずい", "まずい", "not tasty", "word"],
      ["food_076", "甜", "甘い", "あまい", "sweet", "word"],
      ["food_077", "咸", "しょっぱい", "しょっぱい", "salty", "word"],
      ["food_078", "辣", "辛い", "からい", "spicy", "word"],
      ["food_079", "苦", "苦い", "にがい", "bitter", "word"],
      ["food_080", "酸", "酸っぱい", "すっぱい", "sour", "word"],
      ["food_081", "热", "熱い", "あつい", "hot", "word"],
      ["food_082", "冷", "冷たい", "つめたい", "cold", "word"],
      ["food_083", "新鲜", "新鮮", "しんせん", "fresh", "word"],
      ["food_084", "吃饱了", "お腹いっぱい", "おなかいっぱい", "full", "phrase"],
      ["food_085", "饿了", "お腹が空いた", "おなかがすいた", "hungry", "phrase"],
      ["food_086", "渴了", "喉が渇いた", "のどがかわいた", "thirsty", "phrase"],
      ["food_087", "过敏", "アレルギー", "あれるぎー", "allergy", "word"],
      ["food_088", "素食者", "ベジタリアン", "べじたりあん", "vegetarian", "word"],
      ["food_089", "请问有中文菜单吗？", "中国語のメニューはありますか？", "ちゅうごくごのめにゅーはありますか？", "Do you have a Chinese menu?", "phrase"],
      ["food_090", "请给我这个。", "これをください。", "これをください。", "Please give me this one.", "phrase"],
      ["food_091", "不要辣。", "辛くしないでください。", "からくしないでください。", "Not spicy, please.", "phrase"],
      ["food_092", "结账。", "お会計をお願いします。", "おかいけいをおねがいします。", "Check, please.", "phrase"],
      ["food_093", "我可以点餐吗？", "注文してもいいですか？", "ちゅうもんしてもいいですか？", "Can I order?", "phrase"],
      ["food_094", "我对……过敏。", "…にアレルギーがあります。", "…にあれるぎーがあります。", "I am allergic to ...", "phrase"],
      ["food_095", "再来一杯水。", "水をもう一杯ください。", "みずをもういっぱいください。", "One more glass of water, please.", "phrase"],
      ["food_096", "这个好吃吗？", "これはおいしいですか？", "これはおいしいですか？", "Is this delicious?", "phrase"]
    ],

    shopping: [
      ["shopping_001", "商店", "店", "みせ", "shop", "word"],
      ["shopping_002", "商场", "デパート", "でぱーと", "department store", "word"],
      ["shopping_003", "超市", "スーパー", "すーぱー", "supermarket", "word"],
      ["shopping_004", "便利店", "コンビニ", "こんびに", "convenience store", "word"],
      ["shopping_005", "市场", "市場", "いちば", "market", "word"],
      ["shopping_006", "价格", "値段", "ねだん", "price", "word"],
      ["shopping_007", "多少钱", "いくら", "いくら", "how much", "word"],
      ["shopping_008", "贵", "高い", "たかい", "expensive", "word"],
      ["shopping_009", "便宜", "安い", "やすい", "cheap", "word"],
      ["shopping_010", "打折", "割引", "わりびき", "discount", "word"],
      ["shopping_011", "促销", "セール", "せーる", "sale", "word"],
      ["shopping_012", "小票", "レシート", "れしーと", "receipt", "word"],
      ["shopping_013", "现金", "現金", "げんきん", "cash", "word"],
      ["shopping_014", "信用卡", "クレジットカード", "くれじっとかーど", "credit card", "word"],
      ["shopping_015", "银行卡", "キャッシュカード", "きゃっしゅかーど", "bank card", "word"],
      ["shopping_016", "零钱", "小銭", "こぜに", "small change", "word"],
      ["shopping_017", "支付", "支払い", "しはらい", "payment", "word"],
      ["shopping_018", "手机支付", "スマホ決済", "すまほけっさい", "mobile payment", "word"],
      ["shopping_019", "二维码", "二次元コード", "にじげんこーど", "QR code", "word"],
      ["shopping_020", "试衣间", "試着室", "しちゃくしつ", "fitting room", "word"],
      ["shopping_021", "试穿", "試着する", "しちゃくする", "to try on", "word"],
      ["shopping_022", "尺寸", "サイズ", "さいず", "size", "word"],
      ["shopping_023", "大号", "Lサイズ", "えるさいず", "large", "word"],
      ["shopping_024", "中号", "Mサイズ", "えむさいず", "medium", "word"],
      ["shopping_025", "小号", "Sサイズ", "えすさいず", "small", "word"],
      ["shopping_026", "衣服", "服", "ふく", "clothes", "word"],
      ["shopping_027", "衬衫", "シャツ", "しゃつ", "shirt", "word"],
      ["shopping_028", "T恤", "Tシャツ", "てぃーしゃつ", "T-shirt", "word"],
      ["shopping_029", "裤子", "ズボン", "ずぼん", "pants", "word"],
      ["shopping_030", "牛仔裤", "ジーンズ", "じーんず", "jeans", "word"],
      ["shopping_031", "裙子", "スカート", "すかーと", "skirt", "word"],
      ["shopping_032", "连衣裙", "ワンピース", "わんぴーす", "dress", "word"],
      ["shopping_033", "外套", "コート", "こーと", "coat", "word"],
      ["shopping_034", "毛衣", "セーター", "せーたー", "sweater", "word"],
      ["shopping_035", "内衣", "下着", "したぎ", "underwear", "word"],
      ["shopping_036", "袜子", "靴下", "くつした", "socks", "word"],
      ["shopping_037", "鞋子", "靴", "くつ", "shoes", "word"],
      ["shopping_038", "运动鞋", "スニーカー", "すにーかー", "sneakers", "word"],
      ["shopping_039", "帽子", "帽子", "ぼうし", "hat", "word"],
      ["shopping_040", "围巾", "マフラー", "まふらー", "scarf", "word"],
      ["shopping_041", "手套", "手袋", "てぶくろ", "gloves", "word"],
      ["shopping_042", "包", "バッグ", "ばっぐ", "bag", "word"],
      ["shopping_043", "钱包", "財布", "さいふ", "wallet", "word"],
      ["shopping_044", "眼镜", "眼鏡", "めがね", "glasses", "word"],
      ["shopping_045", "太阳镜", "サングラス", "さんぐらす", "sunglasses", "word"],
      ["shopping_046", "手表", "腕時計", "うでどけい", "watch", "word"],
      ["shopping_047", "首饰", "アクセサリー", "あくせさりー", "accessories", "word"],
      ["shopping_048", "化妆品", "化粧品", "けしょうひん", "cosmetics", "word"],
      ["shopping_049", "护肤品", "スキンケア用品", "すきんけあようひん", "skincare", "word"],
      ["shopping_050", "香水", "香水", "こうすい", "perfume", "word"],
      ["shopping_051", "口红", "口紅", "くちべに", "lipstick", "word"],
      ["shopping_052", "洗面奶", "洗顔料", "せんがんりょう", "facial cleanser", "word"],
      ["shopping_053", "食品", "食品", "しょくひん", "food", "word"],
      ["shopping_054", "饮料", "飲み物", "のみもの", "drinks", "word"],
      ["shopping_055", "零食", "お菓子", "おかし", "snacks", "word"],
      ["shopping_056", "纪念品", "お土産", "おみやげ", "souvenir", "word"],
      ["shopping_057", "特产", "名物", "めいぶつ", "local specialty", "word"],
      ["shopping_058", "玩具", "おもちゃ", "おもちゃ", "toy", "word"],
      ["shopping_059", "电子产品", "電子機器", "でんしきき", "electronics", "word"],
      ["shopping_060", "手机", "携帯電話", "けいたいでんわ", "mobile phone", "word"],
      ["shopping_061", "充电器", "充電器", "じゅうでんき", "charger", "word"],
      ["shopping_062", "耳机", "イヤホン", "いやほん", "earphones", "word"],
      ["shopping_063", "相机", "カメラ", "かめら", "camera", "word"],
      ["shopping_064", "电池", "電池", "でんち", "battery", "word"],
      ["shopping_065", "购物袋", "買い物袋", "かいものぶくろ", "shopping bag", "word"],
      ["shopping_066", "环保袋", "エコバッグ", "えこばっぐ", "eco bag", "word"],
      ["shopping_067", "可以退税吗？", "免税できますか？", "めんぜいできますか？", "Is this tax-free?", "phrase"],
      ["shopping_068", "可以便宜一点吗？", "安くしてもらえますか？", "やすくしてもらえますか？", "Can you make it cheaper?", "phrase"],
      ["shopping_069", "我只是看看。", "見ているだけです。", "みているだけです。", "I'm just looking.", "phrase"],
      ["shopping_070", "我要这个。", "これをください。", "これをください。", "I'll take this one.", "phrase"],
      ["shopping_071", "可以刷卡吗？", "カードで払えますか？", "かーどではらえますか？", "Can I pay by card?", "phrase"],
      ["shopping_072", "有没有大一点的？", "もっと大きいのはありますか？", "もっとおおきいのはありますか？", "Do you have a bigger one?", "phrase"],
      ["shopping_073", "可以试穿吗？", "試着してもいいですか？", "しちゃくしてもいいですか？", "Can I try it on?", "phrase"]
    ],

    directions: [
      ["directions_001", "哪里", "どこ", "どこ", "where", "word"],
      ["directions_002", "这里", "ここ", "ここ", "here", "word"],
      ["directions_003", "那里", "あそこ", "あそこ", "over there", "word"],
      ["directions_004", "左边", "左", "ひだり", "left", "word"],
      ["directions_005", "右边", "右", "みぎ", "right", "word"],
      ["directions_006", "前面", "前", "まえ", "front", "word"],
      ["directions_007", "后面", "後ろ", "うしろ", "back", "word"],
      ["directions_008", "旁边", "隣", "となり", "next to", "word"],
      ["directions_009", "对面", "向かい", "むかい", "opposite", "word"],
      ["directions_010", "附近", "近く", "ちかく", "nearby", "word"],
      ["directions_011", "远", "遠い", "とおい", "far", "word"],
      ["directions_012", "近", "近い", "ちかい", "near", "word"],
      ["directions_013", "直走", "まっすぐ", "まっすぐ", "straight", "word"],
      ["directions_014", "转弯", "曲がる", "まがる", "to turn", "word"],
      ["directions_015", "十字路口", "交差点", "こうさてん", "intersection", "word"],
      ["directions_016", "桥", "橋", "はし", "bridge", "word"],
      ["directions_017", "路", "道", "みち", "road", "word"],
      ["directions_018", "街道", "通り", "とおり", "street", "word"],
      ["directions_019", "建筑", "建物", "たてもの", "building", "word"],
      ["directions_020", "派出所", "交番", "こうばん", "police box", "word"],
      ["directions_021", "医院", "病院", "びょういん", "hospital", "word"],
      ["directions_022", "药店", "薬局", "やっきょく", "pharmacy", "word"],
      ["directions_023", "银行", "銀行", "ぎんこう", "bank", "word"],
      ["directions_024", "邮局", "郵便局", "ゆうびんきょく", "post office", "word"],
      ["directions_025", "厕所", "トイレ", "といれ", "toilet", "word"],
      ["directions_026", "公交站", "バス停", "ばすてい", "bus stop", "word"],
      ["directions_027", "地铁站", "地下鉄の駅", "ちかてつのえき", "subway station", "word"],
      ["directions_028", "景点", "観光地", "かんこうち", "tourist spot", "word"],
      ["directions_029", "博物馆", "博物館", "はくぶつかん", "museum", "word"],
      ["directions_030", "公园", "公園", "こうえん", "park", "word"],
      ["directions_031", "请问怎么走？", "どうやって行きますか？", "どうやっていきますか？", "How do I get there?", "phrase"],
      ["directions_032", "……在哪里？", "…はどこですか？", "…はどこですか？", "Where is ...?", "phrase"],
      ["directions_033", "请带我去……", "…まで連れて行ってください。", "…までつれていってください。", "Please take me to ...", "phrase"],
      ["directions_034", "我要去……", "…に行きたいです。", "…にいきたいです。", "I want to go to ...", "phrase"],
      ["directions_035", "走路要几分钟？", "歩いて何分ですか？", "あるいてなんぷんですか？", "How many minutes on foot?", "phrase"],
      ["directions_036", "坐地铁能到吗？", "地下鉄で行けますか？", "ちかてつでいけますか？", "Can I get there by subway?", "phrase"],
      ["directions_037", "我迷路了。", "道に迷いました。", "みちにまよいました。", "I'm lost.", "phrase"],
      ["directions_038", "请问现在在哪里？", "今どこにいますか？", "いまどこにいますか？", "Where am I now?", "phrase"],
      ["directions_039", "请在地图上指给我。", "地図で指してください。", "ちずでさしてください。", "Please point on the map.", "phrase"],
      ["directions_040", "能再说一遍吗？", "もう一度言ってください。", "もういちどいってください。", "Could you say it again?", "phrase"],
      ["directions_041", "怎么去车站？", "駅までどうやって行きますか？", "えきまでどうやっていきますか？", "How do I get to the station?", "phrase"],
      ["directions_042", "这是哪条路？", "この道は何という道ですか？", "このみちはなんというみちですか？", "What street is this?", "phrase"],
      ["directions_043", "洗手间在哪里？", "お手洗いはどこですか？", "おてあらいはどこですか？", "Where is the restroom?", "phrase"]
    ],

    numbers: [
      ["numbers_001", "零", "ゼロ", "ぜろ", "zero", "word"],
      ["numbers_002", "一", "一", "いち", "one", "word"],
      ["numbers_003", "二", "二", "に", "two", "word"],
      ["numbers_004", "三", "三", "さん", "three", "word"],
      ["numbers_005", "四", "四", "よん", "four", "word"],
      ["numbers_006", "五", "五", "ご", "five", "word"],
      ["numbers_007", "六", "六", "ろく", "six", "word"],
      ["numbers_008", "七", "七", "なな", "seven", "word"],
      ["numbers_009", "八", "八", "はち", "eight", "word"],
      ["numbers_010", "九", "九", "きゅう", "nine", "word"],
      ["numbers_011", "十", "十", "じゅう", "ten", "word"],
      ["numbers_012", "百", "百", "ひゃく", "hundred", "word"],
      ["numbers_013", "千", "千", "せん", "thousand", "word"],
      ["numbers_014", "万", "万", "まん", "ten thousand", "word"],
      ["numbers_015", "日元", "円", "えん", "yen", "word"],
      ["numbers_016", "美元", "ドル", "どる", "dollar", "word"],
      ["numbers_017", "人民币", "人民元", "じんみんげん", "yuan", "word"],
      ["numbers_018", "今天", "今日", "きょう", "today", "word"],
      ["numbers_019", "明天", "明日", "あした", "tomorrow", "word"],
      ["numbers_020", "昨天", "昨日", "きのう", "yesterday", "word"],
      ["numbers_021", "后天", "明後日", "あさって", "day after tomorrow", "word"],
      ["numbers_022", "前天", "一昨日", "おととい", "day before yesterday", "word"],
      ["numbers_023", "早上", "朝", "あさ", "morning", "word"],
      ["numbers_024", "中午", "昼", "ひる", "noon", "word"],
      ["numbers_025", "下午", "午後", "ごご", "afternoon", "word"],
      ["numbers_026", "晚上", "夜", "よる", "night", "word"],
      ["numbers_027", "现在", "今", "いま", "now", "word"],
      ["numbers_028", "时间", "時間", "じかん", "time", "word"],
      ["numbers_029", "一小时", "一時間", "いちじかん", "one hour", "word"],
      ["numbers_030", "一分钟", "一分", "いっぷん", "one minute", "word"],
      ["numbers_031", "秒", "秒", "びょう", "second", "word"],
      ["numbers_032", "几点", "何時", "なんじ", "what time", "word"],
      ["numbers_033", "星期", "曜日", "ようび", "day of the week", "word"],
      ["numbers_034", "星期一", "月曜日", "げつようび", "Monday", "word"],
      ["numbers_035", "星期二", "火曜日", "かようび", "Tuesday", "word"],
      ["numbers_036", "星期三", "水曜日", "すいようび", "Wednesday", "word"],
      ["numbers_037", "星期四", "木曜日", "もくようび", "Thursday", "word"],
      ["numbers_038", "星期五", "金曜日", "きんようび", "Friday", "word"],
      ["numbers_039", "星期六", "土曜日", "どようび", "Saturday", "word"],
      ["numbers_040", "星期日", "日曜日", "にちようび", "Sunday", "word"],
      ["numbers_041", "周末", "週末", "しゅうまつ", "weekend", "word"],
      ["numbers_042", "工作日", "平日", "へいじつ", "weekday", "word"],
      ["numbers_043", "日期", "日付", "ひづけ", "date", "word"],
      ["numbers_044", "一月", "一月", "いちがつ", "January", "word"],
      ["numbers_045", "二月", "二月", "にがつ", "February", "word"],
      ["numbers_046", "三月", "三月", "さんがつ", "March", "word"],
      ["numbers_047", "四月", "四月", "しがつ", "April", "word"],
      ["numbers_048", "五月", "五月", "ごがつ", "May", "word"],
      ["numbers_049", "六月", "六月", "ろくがつ", "June", "word"],
      ["numbers_050", "七月", "七月", "しちがつ", "July", "word"],
      ["numbers_051", "八月", "八月", "はちがつ", "August", "word"],
      ["numbers_052", "九月", "九月", "くがつ", "September", "word"],
      ["numbers_053", "十月", "十月", "じゅうがつ", "October", "word"],
      ["numbers_054", "十一月", "十一月", "じゅういちがつ", "November", "word"],
      ["numbers_055", "十二月", "十二月", "じゅうにがつ", "December", "word"],
      ["numbers_056", "一日", "一日", "ついたち", "1st", "word"],
      ["numbers_057", "二日", "二日", "ふつか", "2nd", "word"],
      ["numbers_058", "三日", "三日", "みっか", "3rd", "word"],
      ["numbers_059", "四日", "四日", "よっか", "4th", "word"],
      ["numbers_060", "五日", "五日", "いつか", "5th", "word"],
      ["numbers_061", "六日", "六日", "むいか", "6th", "word"],
      ["numbers_062", "七日", "七日", "なのか", "7th", "word"],
      ["numbers_063", "八日", "八日", "ようか", "8th", "word"],
      ["numbers_064", "九日", "九日", "ここのか", "9th", "word"],
      ["numbers_065", "十日", "十日", "とおか", "10th", "word"],
      ["numbers_066", "今年", "今年", "ことし", "this year", "word"],
      ["numbers_067", "去年", "去年", "きょねん", "last year", "word"],
      ["numbers_068", "明年", "来年", "らいねん", "next year", "word"],
      ["numbers_069", "这个月", "今月", "こんげつ", "this month", "word"],
      ["numbers_070", "上个月", "先月", "せんげつ", "last month", "word"],
      ["numbers_071", "下个月", "来月", "らいげつ", "next month", "word"],
      ["numbers_072", "几点开门？", "何時に開きますか？", "なんじにあきますか？", "What time does it open?", "phrase"],
      ["numbers_073", "现在几点？", "今何時ですか？", "いまなんじですか？", "What time is it now?", "phrase"],
      ["numbers_074", "今天星期几？", "今日は何曜日ですか？", "きょうはなんようびですか？", "What day is it today?", "phrase"],
      ["numbers_075", "今天是几号？", "今日は何日ですか？", "きょうはなんにちですか？", "What date is it today?", "phrase"],
      ["numbers_076", "营业时间", "営業時間", "えいぎょうじかん", "business hours", "word"],
      ["numbers_077", "开门", "開く", "ひらく", "to open", "word"],
      ["numbers_078", "关门", "閉まる", "しまる", "to close", "word"],
      ["numbers_079", "每天", "毎日", "まいにち", "every day", "word"],
      ["numbers_080", "有时", "時々", "ときどき", "sometimes", "word"],
      ["numbers_081", "经常", "よく", "よく", "often", "word"],
      ["numbers_082", "马上", "すぐ", "すぐ", "soon", "word"],
      ["numbers_083", "稍等", "ちょっと待って", "ちょっとまって", "wait a moment", "phrase"]
    ],

    emergency: [
      ["emergency_001", "救命", "助けて", "たすけて", "help", "word"],
      ["emergency_002", "紧急", "緊急", "きんきゅう", "emergency", "word"],
      ["emergency_003", "报警", "警察を呼ぶ", "けいさつをよぶ", "call the police", "word"],
      ["emergency_004", "叫救护车", "救急車を呼ぶ", "きゅうきゅうしゃをよぶ", "call an ambulance", "word"],
      ["emergency_005", "医生", "医者", "いしゃ", "doctor", "word"],
      ["emergency_006", "护士", "看護師", "かんごし", "nurse", "word"],
      ["emergency_007", "药", "薬", "くすり", "medicine", "word"],
      ["emergency_008", "处方", "処方箋", "しょほうせん", "prescription", "word"],
      ["emergency_009", "发烧", "熱", "ねつ", "fever", "word"],
      ["emergency_010", "感冒", "風邪", "かぜ", "cold", "word"],
      ["emergency_011", "咳嗽", "咳", "せき", "cough", "word"],
      ["emergency_012", "头疼", "頭痛", "ずつう", "headache", "word"],
      ["emergency_013", "肚子疼", "腹痛", "ふくつう", "stomachache", "word"],
      ["emergency_014", "牙疼", "歯痛", "しつう", "toothache", "word"],
      ["emergency_015", "恶心", "吐き気", "はきけ", "nausea", "word"],
      ["emergency_016", "呕吐", "嘔吐", "おうと", "vomiting", "word"],
      ["emergency_017", "腹泻", "下痢", "げり", "diarrhea", "word"],
      ["emergency_018", "便秘", "便秘", "べんぴ", "constipation", "word"],
      ["emergency_019", "受伤", "怪我", "けが", "injury", "word"],
      ["emergency_020", "流血", "出血", "しゅっけつ", "bleeding", "word"],
      ["emergency_021", "骨折", "骨折", "こっせつ", "fracture", "word"],
      ["emergency_022", "烫伤", "火傷", "やけど", "burn", "word"],
      ["emergency_023", "哮喘", "喘息", "ぜんそく", "asthma", "word"],
      ["emergency_024", "药片", "錠剤", "じょうざい", "tablet", "word"],
      ["emergency_025", "药膏", "軟膏", "なんこう", "ointment", "word"],
      ["emergency_026", "创可贴", "絆創膏", "ばんそうこう", "band-aid", "word"],
      ["emergency_027", "绷带", "包帯", "ほうたい", "bandage", "word"],
      ["emergency_028", "体温计", "体温計", "たいおんけい", "thermometer", "word"],
      ["emergency_029", "口罩", "マスク", "ますく", "mask", "word"],
      ["emergency_030", "消毒液", "消毒液", "しょうどくえき", "disinfectant", "word"],
      ["emergency_031", "急救箱", "救急箱", "きゅうきゅうばこ", "first aid kit", "word"],
      ["emergency_032", "保险", "保険", "ほけん", "insurance", "word"],
      ["emergency_033", "保险卡", "保険証", "ほけんしょう", "insurance card", "word"],
      ["emergency_034", "我把护照弄丢了。", "パスポートをなくしました。", "ぱすぽーとをなくしました。", "I lost my passport.", "phrase"],
      ["emergency_035", "我的钱包被偷了。", "財布を盗まれました。", "さいふをぬすまれました。", "My wallet was stolen.", "phrase"],
      ["emergency_036", "我需要帮助。", "助けてください。", "たすけてください。", "I need help.", "phrase"],
      ["emergency_037", "请叫警察。", "警察を呼んでください。", "けいさつをよんでください。", "Please call the police.", "phrase"],
      ["emergency_038", "请叫救护车。", "救急車を呼んでください。", "きゅうきゅうしゃをよんでください。", "Please call an ambulance.", "phrase"],
      ["emergency_039", "我不舒服。", "気分が悪いです。", "きぶんがわるいです。", "I feel sick.", "phrase"],
      ["emergency_040", "我生病了。", "病気です。", "びょうきです。", "I am ill.", "phrase"],
      ["emergency_041", "我对……过敏。", "…にアレルギーがあります。", "…にあれるぎーがあります。", "I am allergic to ...", "phrase"],
      ["emergency_042", "哪里有药店？", "薬局はどこですか？", "やっきょくはどこですか？", "Where is a pharmacy?", "phrase"],
      ["emergency_043", "我需要看医生。", "医者に診てもらいたいです。", "いしゃにみてもらいたいです。", "I need to see a doctor.", "phrase"],
      ["emergency_044", "这很紧急。", "緊急です。", "きんきゅうです。", "This is an emergency.", "phrase"]
    ],

    expressions: [
      ["expressions_001", "谢谢", "ありがとう", "ありがとう", "thank you", "word"],
      ["expressions_002", "非常感谢", "ありがとうございます", "ありがとうございます", "thank you very much", "word"],
      ["expressions_003", "不客气", "どういたしまして", "どういたしまして", "you're welcome", "word"],
      ["expressions_004", "请", "ください", "ください", "please", "word"],
      ["expressions_005", "对不起", "すみません", "すみません", "excuse me / sorry", "word"],
      ["expressions_006", "抱歉", "ごめんなさい", "ごめんなさい", "I'm sorry", "word"],
      ["expressions_007", "你好", "こんにちは", "こんにちは", "hello", "word"],
      ["expressions_008", "早上好", "おはようございます", "おはようございます", "good morning", "word"],
      ["expressions_009", "晚上好", "こんばんは", "こんばんは", "good evening", "word"],
      ["expressions_010", "再见", "さようなら", "さようなら", "goodbye", "word"],
      ["expressions_011", "回头见", "またね", "またね", "see you later", "word"],
      ["expressions_012", "晚安", "おやすみなさい", "おやすみなさい", "good night", "word"],
      ["expressions_013", "欢迎光临", "いらっしゃいませ", "いらっしゃいませ", "welcome", "word"],
      ["expressions_014", "我明白了", "わかりました", "わかりました", "I understand", "phrase"],
      ["expressions_015", "我不明白", "わかりません", "わかりません", "I don't understand", "phrase"],
      ["expressions_016", "是的", "はい", "はい", "yes", "word"],
      ["expressions_017", "不是", "いいえ", "いいえ", "no", "word"],
      ["expressions_018", "可以", "大丈夫", "だいじょうぶ", "okay", "word"],
      ["expressions_019", "没关系", "大丈夫です", "だいじょうぶです", "it's okay", "phrase"],
      ["expressions_020", "没问题", "構いません", "かまいません", "no problem", "phrase"],
      ["expressions_021", "好的", "オーケー", "おーけー", "OK", "word"],
      ["expressions_022", "我喜欢", "好きです", "すきです", "I like it", "phrase"],
      ["expressions_023", "我不喜欢", "好きじゃありません", "すきじゃありません", "I don't like it", "phrase"],
      ["expressions_024", "想要", "ほしい", "ほしい", "want", "word"],
      ["expressions_025", "需要", "必要", "ひつよう", "need", "word"],
      ["expressions_026", "有", "あります", "あります", "there is / have", "word"],
      ["expressions_027", "没有", "ありません", "ありません", "there isn't / don't have", "word"],
      ["expressions_028", "是", "です", "です", "is", "word"],
      ["expressions_029", "不是", "じゃありません", "じゃありません", "is not", "phrase"],
      ["expressions_030", "我叫……", "…と申します", "…ともうします", "my name is ...", "phrase"],
      ["expressions_031", "你叫什么名字？", "お名前は何ですか？", "おなまえはなんですか？", "What is your name?", "phrase"],
      ["expressions_032", "我是中国人。", "私は中国人です。", "わたしはちゅうごくじんです。", "I am Chinese.", "phrase"],
      ["expressions_033", "你会说英语吗？", "英語を話せますか？", "えいごをはなせますか？", "Can you speak English?", "phrase"],
      ["expressions_034", "请说慢一点。", "ゆっくり話してください。", "ゆっくりはなしてください。", "Please speak slowly.", "phrase"],
      ["expressions_035", "请再说一遍。", "もう一度言ってください。", "もういちどいってください。", "Please say it again.", "phrase"],
      ["expressions_036", "什么意思？", "どういう意味ですか？", "どういういみですか？", "What does it mean?", "phrase"],
      ["expressions_037", "怎么读？", "どう読みますか？", "どうよみますか？", "How do you read it?", "phrase"],
      ["expressions_038", "怎么写？", "どう書きますか？", "どうかきますか？", "How do you write it?", "phrase"],
      ["expressions_039", "多少钱？", "いくらですか？", "いくらですか？", "How much is it?", "phrase"],
      ["expressions_040", "在哪里？", "どこですか？", "どこですか？", "Where is it?", "phrase"],
      ["expressions_041", "什么时候？", "いつですか？", "いつですか？", "When is it?", "phrase"],
      ["expressions_042", "为什么？", "なぜですか？", "なぜですか？", "Why?", "phrase"],
      ["expressions_043", "怎么办？", "どうすればいいですか？", "どうすればいいですか？", "What should I do?", "phrase"],
      ["expressions_044", "可以吗？", "いいですか？", "いいですか？", "Is it okay?", "phrase"],
      ["expressions_045", "可以。", "いいですよ。", "いいですよ。", "It's fine.", "phrase"],
      ["expressions_046", "不行。", "だめです。", "だめです。", "No / not allowed.", "phrase"],
      ["expressions_047", "有中文吗？", "中国語はありますか？", "ちゅうごくごはありますか？", "Do you have Chinese?", "phrase"]
    ]
  };

  const entries = [];
  Object.keys(groups).forEach((category) => {
    groups[category].forEach((item) => {
      const [id, zh, ja, reading, en, type] = item;
      entries.push({
        id,
        category,
        zh,
        ja,
        reading,
        en,
        type
      });
    });
  });

  return entries;
})();
