"use strict";

// 人工编写的旅行场景例句。每条必须是实际可能说出或听到的完整表达，禁止模板拼接。
module.exports = {
  "jp-ja": {
    airport_001: ["您好，这是我的护照。", "こんにちは、こちらが私のパスポートです。", "こんにちは、こちらがわたしのぱすぽーとです。"],
    airport_002: ["这个签证还在有效期内吗？", "このビザはまだ有効ですか？", "このびざはまだゆうこうですか？"],
    airport_003: ["电子机票保存在我的手机里。", "航空券はスマートフォンに入っています。", "こうくうけんはすまーとふぉんにはいっています。"],
    airport_004: ["请出示您的登机牌。", "搭乗券を見せてください。", "とうじょうけんをみせてください。"],
    airport_005: ["我的行李还没有出来。", "私の荷物がまだ出てきません。", "わたしのにもつがまだでてきません。"],
    airport_006: ["这个行李箱重二十公斤。", "このスーツケースは二十キロあります。", "このすーつけーすはにじゅっきろあります。"],
    airport_007: ["随身行李限带一件。", "機内持ち込み手荷物は一つまでです。", "きないもちこみてにもつはひとつまでです。"],
    airport_008: ["从机场到市区坐什么最方便？", "空港から市内までは何が便利ですか？", "くうこうからしないまではなにがべんりですか？"],
    airport_009: ["国际航班在二号航站楼。", "国際線は第二ターミナルです。", "こくさいせんはだいにたーみなるです。"],
    airport_010: ["出发时间改到下午三点了。", "出発は午後三時に変更されました。", "しゅっぱつはごごさんじにへんこうされました。"],
    airport_011: ["预计晚上七点到达。", "到着は午後七時の予定です。", "とうちゃくはごごしちじのよていです。"],
    airport_012: ["登机口已经变更。", "搭乗口が変更になりました。", "とうじょうぐちがへんこうになりました。"],
    airport_013: ["通过安检大约要多长时间？", "保安検査にはどのくらい時間がかかりますか？", "ほあんけんさにはどのくらいじかんがかかりますか？"],
    airport_014: ["这件物品需要向海关申报吗？", "これは税関で申告する必要がありますか？", "これはぜいかんでしんこくするひつようがありますか？"],
    airport_015: ["我入境日本的目的是旅游。", "日本への入国目的は観光です。", "にほんへのにゅうこくもくてきはかんこうです。"],
    airport_016: ["出境手续在哪里办理？", "出国手続きはどこでしますか？", "しゅっこくてつづきはどこでしますか？"],
    airport_017: ["我要在大阪转乘国内航班。", "大阪で国内線に乗り継ぎます。", "おおさかでこくないせんにのりつぎます。"],
    airport_018: ["这个航班已经满员了。", "この便は満席です。", "このびんはまんせきです。"],
    airport_019: ["航班预计延误三十分钟。", "便は三十分ほど遅延する見込みです。", "びんはさんじゅっぷんほどちえんするみこみです。"],
    airport_020: ["航班取消后可以退款吗？", "便がキャンセルになった場合、払い戻しできますか？", "びんがきゃんせるになったばあい、はらいもどしできますか？"],

    airport_032: ["去市中心的机场大巴从哪里乘坐？", "市内行きの空港バスはどこから乗りますか？", "しないいきのくうこうばすはどこからのりますか？"],
    airport_033: ["请帮我叫一辆出租车。", "タクシーを一台呼んでください。", "たくしーをいちだいよんでください。"],
    airport_034: ["坐地铁去东京站需要换乘吗？", "地下鉄で東京駅まで行くには乗り換えが必要ですか？", "ちかてつでとうきょうえきまでいくにはのりかえがひつようですか？"],
    airport_035: ["这趟电车去新宿吗？", "この電車は新宿に行きますか？", "このでんしゃはしんじゅくにいきますか？"],
    airport_036: ["我想预订明天的新干线指定席。", "明日の新幹線の指定席を予約したいです。", "あしたのしんかんせんのしていせきをよやくしたいです。"],
    airport_037: ["下一班公交车几点来？", "次のバスは何時に来ますか？", "つぎのばすはなんじにきますか？"],
    airport_038: ["最近的车站在哪里？", "一番近い駅はどこですか？", "いちばんちかいえきはどこですか？"],
    airport_039: ["去京都的列车在几号站台？", "京都行きの電車は何番ホームですか？", "きょうといきのでんしゃはなんばんほーむですか？"],
    airport_040: ["请看一下墙上的时刻表。", "壁の時刻表をご覧ください。", "かべのじこくひょうをごらんください。"],
    airport_041: ["请给我一张去奈良的单程票。", "奈良までの片道切符を一枚ください。", "ならまでのかたみちきっぷをいちまいください。"],
    airport_042: ["往返票比两张单程票便宜吗？", "往復切符のほうが安いですか？", "おうふくきっぷのほうがやすいですか？"],
    airport_043: ["我把车票弄丢了。", "切符をなくしてしまいました。", "きっぷをなくしてしまいました。"],
    airport_044: ["售票处晚上几点关门？", "切符売り場は夜何時までですか？", "きっぷうりばはよるなんじまでですか？"],
    airport_045: ["这台自动售票机可以用信用卡吗？", "この自動券売機でクレジットカードは使えますか？", "このじどうけんばいきでくれじっとかーどはつかえますか？"],
    airport_046: ["请在检票口刷交通卡。", "改札口で交通系ICカードをタッチしてください。", "かいさつぐちでこうつうけいあいしーかーどをたっちしてください。"],
    airport_047: ["入口在大楼的右侧。", "入口は建物の右側です。", "いりぐちはたてもののみぎがわです。"],
    airport_048: ["从东出口出去更近。", "東口から出るほうが近いです。", "ひがしぐちからでるほうがちかいです。"],
    airport_049: ["请去问讯处询问失物。", "忘れ物は案内所で聞いてください。", "わすれものはあんないじょできいてください。"],
    airport_050: ["可以在地图上标出这个地方吗？", "地図でこの場所を示してもらえますか？", "ちずでこのばしょをしめしてもらえますか？"],
    airport_051: ["请在这里输入目的地。", "ここに目的地を入力してください。", "ここにもくてきちをにゅうりょくしてください。"],

    hotel_001: ["这家酒店离车站很近。", "このホテルは駅から近いです。", "このほてるはえきからちかいです。"],
    hotel_002: ["这家日式旅馆可以泡温泉。", "この旅館では温泉に入れます。", "このりょかんではおんせんにはいれます。"],
    hotel_003: ["这家民宿包含早餐吗？", "この民宿は朝食付きですか？", "このみんしゅくはちょうしょくつきですか？"],
    hotel_004: ["请把房卡交给前台。", "ルームキーをフロントに預けてください。", "るーむきーをふろんとにあずけてください。"],
    hotel_005: ["我以王这个名字预订了房间。", "王の名前で予約しています。", "わんのなまえでよやくしています。"],
    hotel_006: ["我想现在办理入住。", "今、チェックインをお願いします。", "いま、ちぇっくいんをおねがいします。"],
    hotel_007: ["退房时间是上午十一点。", "チェックアウトは午前十一時です。", "ちぇっくあうとはごぜんじゅういちじです。"],
    hotel_008: ["我的房间在几楼？", "私の部屋は何階ですか？", "わたしのへやはなんがいですか？"],
    hotel_009: ["我预订了一间单人房。", "シングルルームを一部屋予約しました。", "しんぐるるーむをひとへやよやくしました。"],
    hotel_010: ["有两张床的双人房吗？", "ベッドが二台あるツインルームはありますか？", "べっどがにだいあるついんるーむはありますか？"],
    hotel_011: ["大床房可以住两个人吗？", "ダブルルームに二人で泊まれますか？", "だぶるるーむにふたりでとまれますか？"],
    hotel_012: ["这间套房可以看到海。", "このスイートルームから海が見えます。", "このすいーとるーむからうみがみえます。"],
    hotel_013: ["我把房间钥匙忘在里面了。", "部屋に鍵を忘れました。", "へやにかぎをわすれました。"],
    hotel_014: ["我的房卡打不开门。", "ルームキーでドアが開きません。", "るーむきーでどあがあきません。"],
    hotel_015: ["行李员会把行李送到房间。", "ベルボーイが荷物を部屋まで運びます。", "べるぼーいがにもつをへやまではこびます。"],
    hotel_016: ["请问附近有工作人员吗？", "近くにスタッフはいますか？", "ちかくにすたっふはいますか？"],
    hotel_017: ["我想点一份客房服务的早餐。", "ルームサービスで朝食を頼みたいです。", "るーむさーびすでちょうしょくをたのみたいです。"],
    hotel_018: ["今天不需要打扫房间。", "今日は部屋の掃除は不要です。", "きょうはへやのそうじはふようです。"],
    hotel_019: ["可以再给我两条毛巾吗？", "タオルをもう二枚いただけますか？", "たおるをもうにまいいただけますか？"],
    hotel_020: ["请帮我更换床单。", "シーツを交換してください。", "しーつをこうかんしてください。"],

    food_001: ["早餐供应到几点？", "朝食は何時までですか？", "ちょうしょくはなんじまでですか？"],
    food_002: ["午餐套餐包含饮料。", "昼食のセットには飲み物が付きます。", "ちゅうしょくのせっとにはのみものがつきます。"],
    food_003: ["今晚我想在这里吃晚餐。", "今夜はこちらで夕食を食べたいです。", "こんやはこちらでゆうしょくをたべたいです。"],
    food_004: ["可以给我一份英文菜单吗？", "英語のメニューをいただけますか？", "えいごのめにゅーをいただけますか？"],
    food_005: ["准备好后请按这里点菜。", "お決まりになりましたら、こちらで注文してください。", "おきまりになりましたら、こちらでちゅうもんしてください。"],
    food_006: ["请给我一杯水。", "水を一杯ください。", "みずをいっぱいください。"],
    food_007: ["可以给孩子一点热水吗？", "子ども用にお湯をいただけますか？", "こどもようにおゆをいただけますか？"],
    food_008: ["餐后请给我一杯茶。", "食後にお茶をお願いします。", "しょくごにおちゃをおねがいします。"],
    food_009: ["咖啡请不要加糖。", "コーヒーは砂糖なしでお願いします。", "こーひーはさとうなしでおねがいします。"],
    food_010: ["这道菜里含牛奶吗？", "この料理に牛乳は入っていますか？", "このりょうりにぎゅうにゅうははいっていますか？"],
    food_011: ["果汁有橙子和苹果两种。", "ジュースはオレンジとりんごがあります。", "じゅーすはおれんじとりんごがあります。"],
    food_012: ["请先来一杯生啤。", "まず生ビールを一杯ください。", "まずなまびーるをいっぱいください。"],
    food_013: ["这款红酒可以按杯点吗？", "このワインはグラスで頼めますか？", "このわいんはぐらすでたのめますか？"],
    food_014: ["米饭请少一点。", "ご飯は少なめでお願いします。", "ごはんはすくなめでおねがいします。"],
    food_015: ["这个面包是刚烤好的。", "このパンは焼きたてです。", "このぱんはやきたてです。"],
    food_016: ["这种面条很有嚼劲。", "この麺はこしがあります。", "このめんはこしがあります。"],
    food_017: ["这碗拉面可以做得不辣吗？", "このラーメンは辛くしないで作れますか？", "このらーめんはからくしないでつくれますか？"],
    food_018: ["乌冬面请做成热的。", "うどんは温かいものをお願いします。", "うどんはあたたかいものをおねがいします。"],
    food_019: ["我想吃冷荞麦面。", "冷たいそばが食べたいです。", "つめたいそばがたべたいです。"],
    food_020: ["这份寿司里有生鱼。", "この寿司には生魚が入っています。", "このすしにはなまざかながはいっています。"],

    shopping_001: ["这家商店晚上九点关门。", "この店は夜九時に閉まります。", "このみせはよるくじにしまります。"],
    shopping_002: ["车站旁边有一家百货商场。", "駅の隣にデパートがあります。", "えきのとなりにでぱーとがあります。"],
    shopping_003: ["我去超市买些水果。", "スーパーで果物を買います。", "すーぱーでくだものをかいます。"],
    shopping_004: ["便利店全天营业。", "コンビニは二十四時間営業です。", "こんびにはにじゅうよじかんえいぎょうです。"],
    shopping_005: ["这个市场早上最热闹。", "この市場は朝が一番にぎやかです。", "このいちばはあさがいちばんにぎやかです。"],
    shopping_006: ["这个价格包含税吗？", "この値段は税込みですか？", "このねだんはぜいこみですか？"],
    shopping_007: ["这个多少钱？", "これはいくらですか？", "これはいくらですか？"],
    shopping_008: ["有点贵，可以便宜一些吗？", "少し高いので、安くなりますか？", "すこしたかいので、やすくなりますか？"],
    shopping_009: ["这家店的纪念品很便宜。", "この店のお土産は安いです。", "このみせのおみやげはやすいです。"],
    shopping_010: ["出示护照可以打折。", "パスポートを見せると割引になります。", "ぱすぽーとをみせるとわりびきになります。"],
    shopping_011: ["这件外套现在正在促销。", "このコートは今セール中です。", "このこーとはいませーるちゅうです。"],
    shopping_012: ["请给我小票。", "レシートをください。", "れしーとをください。"],
    shopping_013: ["这里只能使用现金。", "こちらは現金のみです。", "こちらはげんきんのみです。"],
    shopping_014: ["可以用信用卡支付吗？", "クレジットカードで払えますか？", "くれじっとかーどではらえますか？"],
    shopping_015: ["这张银行卡在自动取款机上不能用。", "このキャッシュカードはATMで使えません。", "このきゃっしゅかーどはえーてぃーえむでつかえません。"],
    shopping_016: ["自动售货机需要零钱。", "自動販売機には小銭が必要です。", "じどうはんばいきにはこぜにがひつようです。"],
    shopping_017: ["请到一楼柜台付款。", "一階のレジで支払いをお願いします。", "いっかいのれじでしはらいをおねがいします。"],
    shopping_018: ["这里支持手机支付。", "こちらはスマホ決済に対応しています。", "こちらはすまほけっさいにたいおうしています。"],
    shopping_019: ["请扫描这个二维码。", "この二次元コードを読み取ってください。", "このにじげんこーどをよみとってください。"],
    shopping_020: ["试衣间在里面。", "試着室は奥にあります。", "しちゃくしつはおくにあります。"],

    directions_001: ["请问洗手间在哪里？", "すみません、トイレはどこですか？", "すみません、といれはどこですか？"],
    directions_002: ["我们在这里下车。", "私たちはここで降ります。", "わたしたちはここでおります。"],
    directions_003: ["出租车乘车点就在那里。", "タクシー乗り場はあそこです。", "たくしーのりばはあそこです。"],
    directions_004: ["售票处在左边。", "切符売り場は左にあります。", "きっぷうりばはひだりにあります。"],
    directions_005: ["请在下一个路口向右转。", "次の角を右に曲がってください。", "つぎのかどをみぎにまがってください。"],
    directions_006: ["车站就在那栋楼前面。", "駅はあの建物の前です。", "えきはあのたてもののまえです。"],
    directions_007: ["停车场在酒店后面。", "駐車場はホテルの後ろです。", "ちゅうしゃじょうはほてるのうしろです。"],
    directions_008: ["药店就在便利店旁边。", "薬局はコンビニの隣です。", "やっきょくはこんびにのとなりです。"],
    directions_009: ["公交车站在邮局对面。", "バス停は郵便局の向かいです。", "ばすていはゆうびんきょくのむかいです。"],
    directions_010: ["这附近有可以吃饭的地方吗？", "この近くに食事ができる場所はありますか？", "このちかくにしょくじができるばしょはありますか？"],
    directions_011: ["从这里走过去很远吗？", "ここから歩くと遠いですか？", "ここからあるくととおいですか？"],
    directions_012: ["车站很近，步行五分钟。", "駅は近くて、歩いて五分です。", "えきはちかくて、あるいてごふんです。"],
    directions_013: ["沿着这条路一直走。", "この道をまっすぐ進んでください。", "このみちをまっすぐすすんでください。"],
    directions_014: ["过了桥后向左转。", "橋を渡ったら左に曲がってください。", "はしをわたったらひだりにまがってください。"],
    directions_015: ["在第二个十字路口右转。", "二つ目の交差点を右に曲がってください。", "ふたつめのこうさてんをみぎにまがってください。"],
    directions_016: ["过桥就能看到车站。", "橋を渡ると駅が見えます。", "はしをわたるとえきがみえます。"],
    directions_017: ["这条路晚上比较暗。", "この道は夜になると暗いです。", "このみちはよるになるとくらいです。"],
    directions_018: ["这条街上有很多餐厅。", "この通りにはレストランがたくさんあります。", "このとおりにはれすとらんがたくさんあります。"],
    directions_019: ["目的地是那栋白色建筑。", "目的地はあの白い建物です。", "もくてきちはあのしろいたてものです。"],
    directions_020: ["我把钱包交到了派出所。", "財布を交番に届けました。", "さいふをこうばんにとどけました。"],

    emergency_001: ["救命！有人受伤了！", "助けて！人が怪我をしています！", "たすけて！ひとがけがをしています！"],
    emergency_002: ["这是紧急情况。", "これは緊急事態です。", "これはきんきゅうじたいです。"],
    emergency_003: ["请帮我报警。", "警察を呼んでください。", "けいさつをよんでください。"],
    emergency_004: ["请马上叫救护车。", "すぐに救急車を呼んでください。", "すぐにきゅうきゅうしゃをよんでください。"],
    emergency_005: ["我需要看医生。", "医者に診てもらいたいです。", "いしゃにみてもらいたいです。"],
    emergency_006: ["护士马上就过来。", "看護師がすぐに来ます。", "かんごしがすぐにきます。"],
    emergency_007: ["这个药一天吃三次。", "この薬は一日三回飲んでください。", "このくすりはいちにちさんかいのんでください。"],
    emergency_008: ["买这种药需要处方。", "この薬には処方箋が必要です。", "このくすりにはしょほうせんがひつようです。"],
    emergency_009: ["我从昨天开始发烧。", "昨日から熱があります。", "きのうからねつがあります。"],
    emergency_010: ["我可能感冒了。", "風邪をひいたかもしれません。", "かぜをひいたかもしれません。"],
    emergency_011: ["咳嗽一直没有好。", "咳がなかなか治りません。", "せきがなかなかなおりません。"],
    emergency_012: ["我头疼得很厉害。", "頭痛がひどいです。", "ずつうがひどいです。"],
    emergency_013: ["我吃完饭后肚子疼。", "食事の後から腹痛があります。", "しょくじのあとからふくつうがあります。"],
    emergency_014: ["我的牙突然疼起来了。", "急に歯痛が始まりました。", "きゅうにしつうがはじまりました。"],
    emergency_015: ["我感到恶心，吃不下东西。", "吐き気がして、食べられません。", "はきけがして、たべられません。"],
    emergency_016: ["从早上开始一直呕吐。", "朝から嘔吐が続いています。", "あさからおうとがつづいています。"],
    emergency_017: ["我腹泻两天了。", "二日前から下痢が続いています。", "ふつかまえからげりがつづいています。"],
    emergency_018: ["这种药会引起便秘吗？", "この薬で便秘になることはありますか？", "このくすりでべんぴになることはありますか？"],
    emergency_019: ["我摔倒后腿受伤了。", "転んで足を怪我しました。", "ころんであしをけがしました。"],
    emergency_020: ["伤口还在流血。", "傷口からまだ出血しています。", "きずぐちからまだしゅっけつしています。"],

    numbers_001: ["这张卡的余额是零。", "このカードの残高はゼロです。", "このかーどのざんだかはぜろです。"],
    numbers_002: ["请给我一张票。", "切符を一枚ください。", "きっぷをいちまいください。"],
    numbers_003: ["我们一共两个人。", "私たちは二人です。", "わたしたちはふたりです。"],
    numbers_004: ["请给我三瓶水。", "水を三本ください。", "みずをさんぼんください。"],
    numbers_005: ["我们预订了四个晚上。", "四泊で予約しています。", "よんはくでよやくしています。"],
    numbers_006: ["走到车站大约五分钟。", "駅まで歩いて五分くらいです。", "えきまであるいてごふんくらいです。"],
    numbers_007: ["六岁以下的儿童免费。", "六歳未満の子どもは無料です。", "ろくさいみまんのこどもはむりょうです。"],
    numbers_008: ["早餐从七点开始。", "朝食は七時からです。", "ちょうしょくはしちじからです。"],
    numbers_009: ["商店晚上八点关门。", "店は夜八時に閉まります。", "みせはよるはちじにしまります。"],
    numbers_010: ["九号巴士去机场。", "九番のバスは空港に行きます。", "きゅうばんのばすはくうこうにいきます。"],
    numbers_011: ["最多可以等十分钟。", "十分までなら待てます。", "じゅっぷんまでならまてます。"],
    numbers_012: ["这个御守一百日元。", "このお守りは百円です。", "このおまもりはひゃくえんです。"],
    numbers_013: ["这张一日券是一千日元。", "この一日券は千円です。", "このいちにちけんはせんえんです。"],
    numbers_014: ["总计是一万日元。", "合計は一万円です。", "ごうけいはいちまんえんです。"],
    numbers_015: ["我可以用日元支付吗？", "円で支払えますか？", "えんでしはらえますか？"],
    numbers_016: ["这里不能使用美元。", "こちらではドルは使えません。", "こちらではどるはつかえません。"],
    numbers_017: ["可以把人民币兑换成日元吗？", "人民元を円に両替できますか？", "じんみんげんをえんにりょうがえできますか？"],
    numbers_018: ["今天还有空房吗？", "今日、空いている部屋はありますか？", "きょう、あいているへやはありますか？"],
    numbers_019: ["我想预订明天的车票。", "明日の切符を予約したいです。", "あしたのきっぷをよやくしたいです。"],
    numbers_020: ["昨天我把相机落在这里了。", "昨日、ここにカメラを忘れました。", "きのう、ここにかめらをわすれました。"]
  },
  "us-en": {
    airport_001: ["您好，这是我的护照。", "Hi, here's my passport."],
    airport_002: ["这次旅行需要签证吗？", "Do I need a visa for this trip?"],
    airport_003: ["我在网上订了机票。", "I booked my airline ticket online."],
    airport_004: ["您的登机牌在手机上。", "Your boarding pass is on your phone."],
    airport_005: ["我的行李还没到。", "My luggage didn't arrive."],
    airport_006: ["这个行李箱重四十二磅。", "This suitcase weighs forty-two pounds."],
    airport_007: ["每位乘客可以带一件手提行李。", "Each passenger may bring one carry-on bag."],
    airport_008: ["从机场到市中心需要多久？", "How long does it take to get downtown from the airport?"],
    airport_009: ["您的航班从四号航站楼出发。", "Your flight leaves from Terminal 4."],
    airport_010: ["出发时间是下午三点二十分。", "Departure is scheduled for 3:20 p.m."],
    airport_011: ["我们预计晚上七点四十五分到达。", "Our arrival time is 7:45 p.m."],
    airport_012: ["登机口改到 B12 了。", "The boarding gate changed to B12."],
    airport_013: ["安检时请取出笔记本电脑。", "Please take out your laptop at the security checkpoint."],
    airport_014: ["这个需要在海关申报吗？", "Do I need to declare this at customs?"],
    airport_015: ["您这次入境的目的是什么？", "What is the purpose of your entry?"],
    airport_016: ["我星期五离开美国。", "My departure from the United States is on Friday."],
    airport_017: ["我在达拉斯有两个小时转机。", "I have a two-hour connection in Dallas."],
    airport_018: ["这个航班准点吗？", "Is this flight on time?"],
    airport_019: ["航班延误了四十五分钟。", "There's a forty-five-minute delay."],
    airport_020: ["航班取消后我可以退款吗？", "Can I get a refund because of the cancellation?"],

    airport_032: ["机场大巴每三十分钟一班。", "The airport bus runs every thirty minutes."],
    airport_033: ["请帮我叫一辆出租车。", "Could you call a taxi for me?"],
    airport_034: ["坐地铁去市中心最快。", "The subway is the fastest way downtown."],
    airport_035: ["这趟火车去波士顿吗？", "Does this train go to Boston?"],
    airport_036: ["这两个城市之间有高铁吗？", "Is there a high-speed train between these cities?"],
    airport_037: ["这辆公交车在博物馆停吗？", "Does this bus stop at the museum?"],
    airport_038: ["最近的车站在哪里？", "Where is the nearest station?"],
    airport_039: ["去华盛顿的火车从哪个站台发车？", "Which platform does the train to Washington leave from?"],
    airport_040: ["周末的时刻表不一样。", "The weekend timetable is different."],
    airport_041: ["我想买一张去费城的单程票。", "I'd like a one-way ticket to Philadelphia."],
    airport_042: ["一张当天往返票多少钱？", "How much is a same-day round-trip ticket?"],
    airport_043: ["我可以在车上买票吗？", "Can I buy a ticket on the train?"],
    airport_044: ["售票处晚上八点关门。", "The ticket office closes at eight."],
    airport_045: ["这台自动售票机可以刷卡吗？", "Does this ticket machine take cards?"],
    airport_046: ["请在检票口轻触您的卡。", "Tap your card at the ticket gate."],
    airport_047: ["主入口在街角。", "The main entrance is on the corner."],
    airport_048: ["请从下一个出口出去。", "Take the next exit."],
    airport_049: ["您可以到问讯处领取线路图。", "You can get a route map at the information desk."],
    airport_050: ["可以在地图上指给我看吗？", "Could you show me on the map?"],
    airport_051: ["请输入您的目的地。", "Enter your destination, please."],

    hotel_001: ["这家酒店含早餐吗？", "Does this hotel include breakfast?"],
    hotel_002: ["我们在日本住过一家传统日式旅馆。", "We stayed at a traditional Japanese inn in Japan."],
    hotel_003: ["这家民宿有共用厨房。", "This guesthouse has a shared kitchen."],
    hotel_004: ["您可以在前台领取额外的钥匙。", "You can pick up an extra key at the front desk."],
    hotel_005: ["我有一个史密斯名下的预订。", "I have a reservation under Smith."],
    hotel_006: ["下午三点可以办理入住。", "Check-in starts at three p.m."],
    hotel_007: ["最晚几点退房？", "What time is check-out?"],
    hotel_008: ["我的房间还没准备好吗？", "Is my room ready yet?"],
    hotel_009: ["有安静一点的单人房吗？", "Do you have a quiet single room?"],
    hotel_010: ["我们想要一间有两张床的双人房。", "We'd like a twin room with two beds."],
    hotel_011: ["我预订的是一间大床房。", "I reserved a double room."],
    hotel_012: ["这间套房有独立客厅吗？", "Does this suite have a separate living room?"],
    hotel_013: ["我把钥匙落在房间里了。", "I left my key in the room."],
    hotel_014: ["我的房卡打不开门。", "My room key won't open the door."],
    hotel_015: ["行李员会把您的行李送到楼上。", "The bell attendant will bring your bags upstairs."],
    hotel_016: ["工作人员非常热心。", "The staff was very helpful."],
    hotel_017: ["客房服务供应到晚上十一点。", "Room service is available until eleven p.m."],
    hotel_018: ["今天不用打扫房间，谢谢。", "I don't need housekeeping today, thank you."],
    hotel_019: ["可以再送两条毛巾吗？", "Could you send up two more towels?"],
    hotel_020: ["床单上有一块污渍。", "There's a stain on the bed sheet."],

    food_001: ["早餐供应到几点？", "What time does breakfast end?"],
    food_002: ["午餐有套餐吗？", "Do you have a lunch special?"],
    food_003: ["今晚两位用餐，有空桌吗？", "Do you have a table for two for dinner tonight?"],
    food_004: ["可以给我一份菜单吗？", "Could I see a menu, please?"],
    food_005: ["我们可以点餐了吗？", "We're ready to order."],
    food_006: ["请给我一杯不加冰的水。", "Could I have water with no ice?"],
    food_007: ["可以给我一些热水吗？", "Could I get some hot water?"],
    food_008: ["您有不含咖啡因的茶吗？", "Do you have decaf tea?"],
    food_009: ["请给我一杯加燕麦奶的咖啡。", "I'd like a coffee with oat milk."],
    food_010: ["这个酱汁里有牛奶吗？", "Is there milk in this sauce?"],
    food_011: ["请给孩子一杯小杯苹果汁。", "A small apple juice for the child, please."],
    food_012: ["你们有本地精酿啤酒吗？", "Do you have any local craft beer?"],
    food_013: ["请给我一杯佐餐红酒。", "I'd like a glass of red wine with dinner."],
    food_014: ["这个可以把薯条换成米饭吗？", "Can I substitute rice for the fries?"],
    food_015: ["面包可以免费续吗？", "Are bread refills complimentary?"],
    food_016: ["这些面条可以做得不辣吗？", "Can you make these noodles mild?"],
    food_017: ["这碗拉面是用猪骨汤做的吗？", "Is this ramen made with pork broth?"],
    food_018: ["我想要一份蔬菜乌冬面。", "I'd like the vegetable udon."],
    food_019: ["荞麦面里含麸质吗？", "Do the soba noodles contain gluten?"],
    food_020: ["请来一份三文鱼寿司外带。", "I'd like an order of salmon sushi to go."],

    shopping_001: ["这家商店星期天营业吗？", "Is this shop open on Sundays?"],
    shopping_002: ["百货商场的鞋区在几楼？", "What floor is the shoe department on?"],
    shopping_003: ["这家超市有熟食区吗？", "Does this supermarket have a deli?"],
    shopping_004: ["附近有二十四小时便利店吗？", "Is there a twenty-four-hour convenience store nearby?"],
    shopping_005: ["周六的农贸市场在哪里？", "Where is the farmers' market on Saturday?"],
    shopping_006: ["这个价格含销售税吗？", "Does this price include sales tax?"],
    shopping_007: ["加税后一共多少钱？", "How much is it with tax?"],
    shopping_008: ["这个对我的预算来说太贵了。", "That's too expensive for my budget."],
    shopping_009: ["有更便宜的款式吗？", "Do you have a cheaper option?"],
    shopping_010: ["学生可以享受折扣吗？", "Is there a student discount?"],
    shopping_011: ["这件夹克现在打折。", "This jacket is on sale right now."],
    shopping_012: ["请把小票放进袋子里。", "Please put the receipt in the bag."],
    shopping_013: ["我可以用现金支付。", "I can pay in cash."],
    shopping_014: ["你们接受这张信用卡吗？", "Do you accept this credit card?"],
    shopping_015: ["我的银行卡被拒了。", "My bank card was declined."],
    shopping_016: ["您有二十美元的零钱吗？", "Do you have change for a twenty?"],
    shopping_017: ["付款没有成功。", "The payment didn't go through."],
    shopping_018: ["我可以用手机支付吗？", "Can I pay with my phone?"],
    shopping_019: ["请扫描收据上的二维码。", "Scan the QR code on the receipt."],
    shopping_020: ["试衣间在哪里？", "Where is the fitting room?"],

    directions_001: ["洗手间在哪里？", "Where is the restroom?"],
    directions_002: ["我们现在在这里。", "We're right here."],
    directions_003: ["公交站就在那边。", "The bus stop is over there."],
    directions_004: ["银行在你的左边。", "The bank will be on your left."],
    directions_005: ["在红绿灯处向右转。", "Turn right at the light."],
    directions_006: ["出租车就在酒店前面。", "The taxi is in front of the hotel."],
    directions_007: ["停车场在大楼后面。", "The parking lot is behind the building."],
    directions_008: ["药店就在咖啡馆旁边。", "The pharmacy is next to the cafe."],
    directions_009: ["博物馆在公园对面。", "The museum is across from the park."],
    directions_010: ["附近有 ATM 吗？", "Is there an ATM nearby?"],
    directions_011: ["从这里走过去远吗？", "Is it far to walk from here?"],
    directions_012: ["火车站离这里很近。", "The train station is close by."],
    directions_013: ["直走两个街区。", "Go straight for two blocks."],
    directions_014: ["过桥后向左转。", "Turn left after the bridge."],
    directions_015: ["在下一个十字路口和我会合。", "Meet me at the next intersection."],
    directions_016: ["过桥后您会看到酒店。", "You'll see the hotel after you cross the bridge."],
    directions_017: ["这条路通往国家公园吗？", "Does this road lead to the national park?"],
    directions_018: ["我们在第五大街上。", "We're on Fifth Avenue."],
    directions_019: ["那座玻璃大楼就是图书馆。", "The glass building is the library."],
    directions_020: ["最近的警察局在哪里？", "Where is the nearest police station?"],

    emergency_001: ["救命！有人受伤了！", "Help! Someone is hurt!"],
    emergency_002: ["这是医疗紧急情况。", "This is a medical emergency."],
    emergency_003: ["请报警，我的钱包被偷了。", "Please call the police. My wallet was stolen."],
    emergency_004: ["请叫救护车。", "Please call an ambulance."],
    emergency_005: ["我今天需要看医生。", "I need to see a doctor today."],
    emergency_006: ["护士会测量您的血压。", "The nurse will check your blood pressure."],
    emergency_007: ["这种药多久服用一次？", "How often should I take this medicine?"],
    emergency_008: ["在美国，这种药需要处方吗？", "Do I need a prescription for this medicine in the U.S.?"],
    emergency_009: ["我从昨晚开始发烧。", "I've had a fever since last night."],
    emergency_010: ["我可能只是感冒了。", "I think I just have a cold."],
    emergency_011: ["这种咳嗽持续了三天。", "I've had this cough for three days."],
    emergency_012: ["我头疼得很厉害。", "I have a severe headache."],
    emergency_013: ["吃过晚饭后我开始胃疼。", "My stomachache started after dinner."],
    emergency_014: ["我需要找急诊牙医治疗牙疼。", "I need an emergency dentist for this toothache."],
    emergency_015: ["这种药让我感到恶心。", "This medicine is making me nauseous."],
    emergency_016: ["我从早上起一直在呕吐。", "I've been vomiting since this morning."],
    emergency_017: ["我旅行时开始腹泻。", "I developed diarrhea while traveling."],
    emergency_018: ["这会缓解便秘吗？", "Will this help with constipation?"],
    emergency_019: ["我摔倒了，膝盖受伤。", "I fell and injured my knee."],
    emergency_020: ["伤口一直在流血。", "The cut won't stop bleeding."],

    numbers_001: ["这项服务没有额外费用。", "There is zero extra charge for this service."],
    numbers_002: ["我只需要一张票。", "I only need one ticket."],
    numbers_003: ["请给我们一张两人桌。", "A table for two, please."],
    numbers_004: ["我们住三个晚上。", "We're staying for three nights."],
    numbers_005: ["我们一行四个人。", "There are four people in our group."],
    numbers_006: ["步行只要五分钟。", "It's only a five-minute walk."],
    numbers_007: ["六岁以下儿童免费。", "Children under six are free."],
    numbers_008: ["商店晚上七点关门。", "The store closes at seven p.m."],
    numbers_009: ["早餐从早上八点开始。", "Breakfast starts at eight a.m."],
    numbers_010: ["乘九路公交车去市中心。", "Take bus number nine downtown."],
    numbers_011: ["最多需要十分钟。", "It should take no more than ten minutes."],
    numbers_012: ["这张钞票是一百美元。", "This bill is one hundred dollars."],
    numbers_013: ["租车押金是一千美元。", "The rental car deposit is one thousand dollars."],
    numbers_014: ["演唱会吸引了一万名观众。", "The concert drew ten thousand people."],
    numbers_015: ["这家店不接受日元。", "This store doesn't accept yen."],
    numbers_016: ["我可以用美元付款吗？", "Can I pay in U.S. dollars?"],
    numbers_017: ["我在哪里可以把人民币兑换成美元？", "Where can I exchange yuan for dollars?"],
    numbers_018: ["今天还有去芝加哥的航班吗？", "Are there any flights to Chicago today?"],
    numbers_019: ["我想预订明天上午的行程。", "I'd like to book the trip for tomorrow morning."],
    numbers_020: ["我昨天把太阳镜落在出租车上了。", "I left my sunglasses in a taxi yesterday."]
  }
};
