"use strict";

// Hand-written examples for Spain Spanish. Each list follows the order of the
// source words that expose an example. Keeping these outside the generator
// makes linguistic review possible and prevents template + word accidents.
module.exports = {
  airport: [
    ["这是我的护照。", "Aquí tiene mi pasaporte."],
    ["入境西班牙需要签证吗？", "¿Necesito visado para entrar en España?"],
    ["我想更改机票。", "Quisiera cambiar mi billete de avión."],
    ["需要打印登机牌吗？", "¿Tengo que imprimir la tarjeta de embarque?"],
    ["这件行李可以托运吗？", "¿Puedo facturar este equipaje?"],
    ["我的行李箱没有出来。", "Mi maleta no ha salido por la cinta."],
    ["这件手提行李符合尺寸要求吗？", "¿Este equipaje de mano cumple las medidas?"],
    ["去机场怎么走？", "¿Cómo se llega al aeropuerto?"],
    ["这个航班从哪个航站楼出发？", "¿De qué terminal sale este vuelo?"],
    ["出发区在楼上。", "La zona de salidas está arriba."],
    ["请看屏幕上的到达信息。", "Mire las llegadas en la pantalla."],
    ["登机口换了吗？", "¿Ha cambiado la puerta de embarque?"],
    ["安检大约需要多长时间？", "¿Cuánto se tarda en pasar el control de seguridad?"],
    ["我没有需要向海关申报的物品。", "No tengo nada que declarar en la aduana."],
    ["入境时要填写这张表吗？", "¿Tengo que rellenar este formulario para entrar en el país?"],
    ["离境检查在哪里？", "¿Dónde está el control de salida del país?"],
    ["我在马德里转机。", "Tengo una escala en Madrid."],
    ["我的航班几点起飞？", "¿A qué hora sale mi vuelo?"],
    ["航班延误了两个小时。", "El vuelo lleva dos horas de retraso."],
    ["航班取消后我该怎么办？", "¿Qué hago si han cancelado el vuelo?"],
    ["值机柜台已经开了吗？", "¿Ya está abierto el mostrador de facturación?"],
    ["登机已经开始了。", "Ya ha empezado el embarque."],
    ["起飞前请关闭手机。", "Apague el móvil antes del despegue, por favor."],
    ["着陆时请系好安全带。", "Abróchese el cinturón durante el aterrizaje."],
    ["有飞往巴塞罗那的直飞航班吗？", "¿Hay algún vuelo directo a Barcelona?"],
    ["哪里可以寄存行李？", "¿Dónde está la consigna de equipaje?"],
    ["我需要申报行李丢失。", "Necesito comunicar que se ha perdido mi equipaje."],
    ["这个可以作为手提行李带上飞机吗？", "¿Puedo llevar esto como equipaje de mano?"],
    ["我想托运这个行李箱。", "Quiero facturar esta maleta."],
    ["我需要填写海关申报单吗？", "¿Tengo que rellenar una declaración de aduanas?"],
    ["我想申请延长签证。", "Quisiera solicitar una prórroga del visado."],
    ["超重行李要付多少钱？", "¿Cuánto tengo que pagar por el exceso de equipaje?"]
  ],
  transport: [
    ["机场大巴在哪里乘坐？", "¿Dónde se coge el autobús del aeropuerto?"],
    ["请帮我叫一辆出租车。", "¿Puede llamarme un taxi, por favor?"],
    ["去市中心可以坐地铁。", "Puede ir al centro en metro."],
    ["这趟火车去塞维利亚吗？", "¿Este tren va a Sevilla?"],
    ["去马德里的高铁从哪个站台开？", "¿De qué andén sale el tren de alta velocidad a Madrid?"],
    ["下一班公交车几点到？", "¿A qué hora llega el próximo autobús?"],
    ["车站离这里远吗？", "¿Está lejos la estación?"],
    ["我们的火车在三号站台。", "Nuestro tren sale del andén tres."],
    ["我在哪里能看时刻表？", "¿Dónde puedo consultar el horario?"],
    ["请给我一张去托莱多的单程票。", "Un billete de ida a Toledo, por favor."],
    ["我想买一张往返票。", "Quisiera un billete de ida y vuelta."],
    ["这张票需要检票吗？", "¿Hay que validar este billete?"],
    ["售票窗口几点关门？", "¿A qué hora cierra la taquilla?"],
    ["可以在自动售票机上用银行卡吗？", "¿Se puede pagar con tarjeta en la máquina expendedora?"],
    ["请把车票放在闸机上。", "Acerque el billete al torno de acceso."],
    ["地铁入口在广场旁边。", "La entrada del metro está junto a la plaza."],
    ["出口在左边。", "La salida está a la izquierda."],
    ["我去问一下服务台。", "Voy a preguntar en la oficina de información."],
    ["可以在地图上标出来吗？", "¿Puede señalarlo en el mapa?"],
    ["我的目的地是格拉纳达。", "Mi destino es Granada."],
    ["我想租一辆自动挡汽车。", "Quisiera alquilar un coche automático."],
    ["从这里可以步行过去吗？", "¿Se puede ir a pie desde aquí?"]
  ],
  hotel: [
    ["这家酒店有二十四小时前台吗？", "¿Este hotel tiene recepción las veinticuatro horas?"],
    ["我们想住一家有特色的国营古堡酒店。", "Nos gustaría alojarnos en un parador."],
    ["这个旅游住宿登记过吗？", "¿Está registrado este alojamiento turístico?"],
    ["请到前台领取房卡。", "Recoja la tarjeta en recepción, por favor."],
    ["我用这个名字订了房。", "Tengo una reserva a este nombre."],
    ["入住时间是下午三点。", "La entrada es a partir de las tres de la tarde."],
    ["退房时间是中午十二点。", "La salida es antes de las doce."],
    ["房间还没准备好吗？", "¿Todavía no está lista la habitación?"],
    ["我预订的是单人间。", "He reservado una habitación individual."],
    ["我们想要一间双床房。", "Queremos una habitación con dos camas."],
    ["双人间包含早餐吗？", "¿La habitación doble incluye el desayuno?"],
    ["这间套房可以住三个人吗？", "¿Pueden alojarse tres personas en la suite?"],
    ["我把房间钥匙落在里面了。", "Me he dejado la llave dentro de la habitación."],
    ["我的房卡打不开门。", "La tarjeta de la habitación no abre la puerta."],
    ["行李员可以帮您拿行李。", "El botones puede ayudarle con el equipaje."],
    ["工作人员非常友好。", "El personal es muy amable."],
    ["客房服务到几点？", "¿Hasta qué hora funciona el servicio de habitaciones?"],
    ["今天不用打扫房间。", "Hoy no hace falta limpiar la habitación."],
    ["可以再给我一条毛巾吗？", "¿Me puede traer otra toalla?"],
    ["床单上有一处污渍。", "Hay una mancha en la sábana."],
    ["请明早七点叫醒我。", "Quisiera el servicio de despertador a las siete."],
    ["酒店有洗衣服务吗？", "¿El hotel tiene servicio de lavandería?"],
    ["今晚还有空房吗？", "¿Hay alguna habitación disponible para esta noche?"],
    ["很抱歉，酒店已经满房了。", "Lo siento, el hotel está completo."],
    ["入住时需要交押金吗？", "¿Hay que dejar una fianza al entrar?"],
    ["可以把账单发到我的邮箱吗？", "¿Puede enviarme la cuenta por correo electrónico?"],
    ["我想要一间安静的房间。", "Quisiera una habitación tranquila."],
    ["我的房间晚上很吵。", "Mi habitación es muy ruidosa por la noche."],
    ["这张床很舒服。", "Esta cama es muy cómoda."],
    ["我可以延住一晚吗？", "¿Puedo prolongar la estancia una noche más?"]
  ],
  food: [
    ["早餐供应到几点？", "¿Hasta qué hora sirven el desayuno?"],
    ["我们想在这里吃午饭。", "Queremos comer aquí."],
    ["今晚可以订一张桌子吗？", "¿Podemos reservar una mesa para cenar esta noche?"],
    ["可以给我看一下菜单吗？", "¿Me trae la carta, por favor?"],
    ["我们可以点餐了吗？", "¿Podemos pedir ya?"],
    ["请给我一瓶不带气的水。", "Una botella de agua sin gas, por favor."],
    ["可以给我一杯热水吗？", "¿Me puede traer un vaso de agua caliente?"],
    ["我想喝一杯红茶。", "Quisiera un té negro."],
    ["请给我一杯加牛奶的咖啡。", "Un café con leche, por favor."],
    ["这道菜里有牛奶吗？", "¿Este plato lleva leche?"],
    ["请给我一杯鲜榨橙汁。", "Un zumo de naranja natural, por favor."],
    ["请给我一杯生啤。", "Una cerveza de barril, por favor."],
    ["可以推荐一款西班牙红酒吗？", "¿Me recomienda un vino tinto español?"],
    ["米饭可以单点吗？", "¿Se puede pedir arroz como acompañamiento?"],
    ["可以再给我们一些面包吗？", "¿Nos trae un poco más de pan?"],
    ["这道菜配的是面条吗？", "¿Este plato viene con fideos?"],
    ["我们想点几份西班牙小吃。", "Queremos pedir unas tapas."],
    ["西班牙土豆饼里有洋葱吗？", "¿La tortilla española lleva cebolla?"],
    ["请给我们一份海鲜饭。", "Una paella, por favor."],
    ["这份西班牙冷汤是凉的吗？", "¿El gazpacho se sirve frío?"],
    ["请结账。", "La cuenta, por favor."],
    ["这份请打包带走。", "Esto es para llevar, por favor."],
    ["这道海鲜饭很好吃。", "Esta paella está muy rica."],
    ["这道菜味道不太好。", "Este plato no sabe muy bien."],
    ["这个甜点太甜了。", "Este postre está demasiado dulce."],
    ["汤有点咸。", "La sopa está un poco salada."],
    ["这个酱辣吗？", "¿Esta salsa es picante?"],
    ["咖啡有点苦。", "El café está un poco amargo."],
    ["这个柠檬很酸。", "Este limón está muy ácido."],
    ["小心，盘子很烫。", "Cuidado, el plato está caliente."],
    ["我想喝点冰水。", "Quisiera agua fría."],
    ["今天的鱼新鲜吗？", "¿El pescado es fresco de hoy?"],
    ["我对贝类过敏。", "Tengo alergia al marisco."],
    ["你们有素食菜品吗？", "¿Tienen algún plato vegetariano?"]
  ],
  shopping: [
    ["这家店几点关门？", "¿A qué hora cierra esta tienda?"],
    ["附近有百货商店吗？", "¿Hay unos grandes almacenes cerca?"],
    ["超市在地下层。", "El supermercado está en la planta baja."],
    ["这附近有便利店吗？", "¿Hay alguna tienda de conveniencia por aquí?"],
    ["周日市场开门吗？", "¿Abre el mercado los domingos?"],
    ["这个价格含税吗？", "¿Este precio incluye el IVA?"],
    ["请问这个多少钱？", "¿Cuánto cuesta esto?"],
    ["对我来说有点贵。", "Me parece un poco caro."],
    ["有没有更便宜的？", "¿Tiene alguno más barato?"],
    ["学生可以享受折扣吗？", "¿Hay descuento para estudiantes?"],
    ["这件商品在促销吗？", "¿Este artículo está de oferta?"],
    ["可以给我购物小票吗？", "¿Me da el tique, por favor?"],
    ["我可以用现金付款。", "Puedo pagar en efectivo."],
    ["你们接受信用卡吗？", "¿Aceptan tarjetas de crédito?"],
    ["我的银行卡被拒绝了。", "Han rechazado mi tarjeta bancaria."],
    ["您有零钱吗？", "¿Tiene cambio?"],
    ["在哪里付款？", "¿Dónde se paga?"],
    ["可以用手机支付吗？", "¿Puedo pagar con el móvil?"],
    ["请扫描这个二维码。", "Escanee este código QR, por favor."],
    ["试衣间在哪里？", "¿Dónde está el probador?"],
    ["我可以试穿这件吗？", "¿Me puedo probar esto?"],
    ["我想买一些当地特产。", "Quisiera comprar algún producto local."]
  ],
  directions: [
    ["请问地铁站在哪里？", "¿Dónde está la estación de metro?"],
    ["我们现在在这里。", "Ahora estamos aquí."],
    ["售票处在那边。", "La taquilla está allí."],
    ["在下一个路口左转。", "Gire a la izquierda en el próximo cruce."],
    ["银行在右边。", "El banco está a la derecha."],
    ["博物馆就在前面。", "El museo está delante."],
    ["停车场在酒店后面。", "El aparcamiento está detrás del hotel."],
    ["药店就在邮局旁边。", "La farmacia está al lado de Correos."],
    ["餐厅在车站对面。", "El restaurante está enfrente de la estación."],
    ["附近有公共洗手间吗？", "¿Hay un aseo público cerca?"],
    ["机场离市中心很远。", "El aeropuerto está lejos del centro."],
    ["最近的药店在哪里？", "¿Dónde está la farmacia más cercana?"],
    ["一直往前走两百米。", "Siga todo recto unos doscientos metros."],
    ["到了广场后向右转。", "Al llegar a la plaza, gire a la derecha."],
    ["在第二个十字路口左转。", "Gire a la izquierda en el segundo cruce."],
    ["过桥以后就是车站。", "La estación está justo después del puente."],
    ["这条公路通往机场。", "Esta carretera lleva al aeropuerto."],
    ["这条街叫什么名字？", "¿Cómo se llama esta calle?"],
    ["那栋白色建筑就是市政厅。", "Ese edificio blanco es el ayuntamiento."],
    ["最近的警察局在哪里？", "¿Dónde está la comisaría más cercana?"]
  ],
  emergency: [
    ["救命！有人受伤了！", "¡Socorro! ¡Hay una persona herida!"],
    ["这是紧急情况。", "Es una emergencia."],
    ["请马上报警。", "Llame a la policía ahora mismo, por favor."],
    ["我们需要叫救护车。", "Necesitamos llamar a una ambulancia."],
    ["我需要看医生。", "Necesito ver a un médico."],
    ["可以请护士过来吗？", "¿Puede venir un enfermero, por favor?"],
    ["这种药一天吃几次？", "¿Cuántas veces al día tengo que tomar este medicamento?"],
    ["买这个需要处方吗？", "¿Hace falta receta para comprarlo?"],
    ["我发烧到三十九度。", "Tengo treinta y nueve grados de fiebre."],
    ["我好像感冒了。", "Creo que estoy resfriado."],
    ["我咳嗽了三天。", "Tengo tos desde hace tres días."],
    ["我头疼得很厉害。", "Me duele mucho la cabeza."],
    ["我从昨晚开始胃痛。", "Me duele el estómago desde anoche."],
    ["我需要找牙医，我牙疼。", "Necesito un dentista; me duelen las muelas."],
    ["我感到恶心。", "Tengo náuseas."],
    ["我一直在呕吐。", "No paro de vomitar."],
    ["我腹泻了。", "Tengo diarrea."],
    ["这种药会导致便秘吗？", "¿Este medicamento puede causar estreñimiento?"],
    ["伤口需要缝合吗？", "¿Hay que dar puntos en la herida?"],
    ["怎样才能止血？", "¿Cómo puedo detener el sangrado?"],
    ["我担心骨折了。", "Creo que puede ser una fractura."],
    ["这个烫伤需要去医院吗？", "¿Tengo que ir al hospital por esta quemadura?"],
    ["我有哮喘，需要吸入器。", "Tengo asma y necesito un inhalador."],
    ["我的旅行保险包含急诊吗？", "¿Mi seguro de viaje cubre las urgencias?"]
  ],
  basics: [
    ["费用是零欧元。", "El coste es de cero euros."],
    ["我需要一张票。", "Necesito un billete."],
    ["我们有两件行李。", "Tenemos dos maletas."],
    ["请给我们一张三人桌。", "Una mesa para tres, por favor."],
    ["我们住四晚。", "Nos quedamos cuatro noches."],
    ["五分钟后见。", "Nos vemos en cinco minutos."],
    ["六点可以吗？", "¿A las seis le viene bien?"],
    ["请早上七点叫醒我。", "Despiérteme a las siete, por favor."],
    ["商店八点开门。", "La tienda abre a las ocho."],
    ["火车九点出发。", "El tren sale a las nueve."],
    ["步行需要十分钟。", "Se tarda diez minutos andando."],
    ["这件东西一百欧元。", "Esto cuesta cien euros."],
    ["这个城市有一千多年的历史。", "Esta ciudad tiene más de mil años de historia."],
    ["这里大约有一万人。", "Aquí viven unas diez mil personas."],
    ["这张纸币是十欧元。", "Este billete es de diez euros."],
    ["我想把美元换成欧元。", "Quiero cambiar dólares por euros."],
    ["可以把人民币换成欧元吗？", "¿Puedo cambiar yuanes por euros?"],
    ["今天博物馆开门吗？", "¿Está abierto hoy el museo?"],
    ["我们明天去塞维利亚。", "Mañana vamos a Sevilla."],
    ["我昨天到的马德里。", "Llegué ayer a Madrid."],
    ["请问现在几点？", "¿Qué hora es?"],
    ["博物馆几点开门？", "¿A qué hora abre el museo?"],
    ["商店九点关门。", "La tienda cierra a las nueve."],
    ["救护车马上就到。", "La ambulancia llegará enseguida."],
    ["谢谢您的帮助。", "Gracias por su ayuda."],
    ["真的非常感谢。", "Muchísimas gracias."],
    ["不客气。", "De nada."],
    ["请给我一张地图。", "Un mapa, por favor."],
    ["劳驾，火车站在哪里？", "Perdone, ¿dónde está la estación?"],
    ["对不起，我听不懂。", "Lo siento, no entiendo."],
    ["你好，我有一个预订。", "Hola, tengo una reserva."],
    ["早上好，请问有空房吗？", "Buenos días, ¿tienen alguna habitación libre?"],
    ["下午好，我想办理入住。", "Buenas tardes, quisiera registrarme."],
    ["再见，祝您愉快。", "Adiós, que tenga un buen día."],
    ["回头见，谢谢！", "Hasta luego, ¡gracias!"],
    ["晚安，明天见。", "Buenas noches, hasta mañana."],
    ["欢迎来到西班牙。", "Bienvenido a España."],
    ["是的，我有预订。", "Sí, tengo una reserva."],
    ["不，谢谢。", "No, gracias."],
    ["好的，我们走吧。", "Vale, vamos."],
    ["好的，我同意。", "De acuerdo, estoy conforme."],
    ["我想要靠窗的座位。", "Quiero un asiento junto a la ventanilla."],
    ["我需要一名医生。", "Necesito un médico."],
    ["附近有药店吗？", "¿Hay una farmacia cerca?"],
    ["现在没有空桌。", "No hay ninguna mesa libre ahora."],
    ["这是去市中心的公交车。", "Este es el autobús que va al centro."]
  ]
};
