"use strict";

// Thirty reviewed expansion phrases per scene, matching en_<scene>_phrase_001
// through _030. These are real travel utterances, not word-slot templates.
module.exports = {
  airport: [
    ["请问护照检查在哪里？", "¿Dónde está el control de pasaportes?"],
    ["我的签证有问题，可以帮我吗？", "Tengo un problema con el visado, ¿puede ayudarme?"],
    ["可以确认一下机票上的日期吗？", "¿Puede comprobar la fecha de mi billete?"],
    ["我的航班从哪个航站楼出发？", "¿De qué terminal sale mi vuelo?"],
    ["这张登机牌可以用吗？", "¿Es válida esta tarjeta de embarque?"],
    ["值机柜台在哪里？", "¿Dónde está el mostrador de facturación?"],
    ["我想换一个座位。", "Quisiera cambiar de asiento."],
    ["还有靠窗的座位吗？", "¿Queda algún asiento junto a la ventanilla?"],
    ["可以给我一个靠过道的座位吗？", "¿Me puede dar un asiento junto al pasillo?"],
    ["我可以免费托运几件行李？", "¿Cuántas piezas de equipaje puedo facturar gratis?"],
    ["我的行李箱在运输中损坏了。", "Mi maleta ha sufrido daños durante el viaje."],
    ["这件行李可以带进客舱吗？", "¿Puedo llevar este equipaje en la cabina?"],
    ["这个航班的行李在几号转盘？", "¿En qué cinta sale el equipaje de este vuelo?"],
    ["哪里可以找到行李推车？", "¿Dónde puedo encontrar un carrito para el equipaje?"],
    ["这是排队过安检的队伍吗？", "¿Es esta la cola para el control de seguridad?"],
    ["免税店在安检后面吗？", "¿La tienda libre de impuestos está después del control?"],
    ["候机区有充电插座吗？", "¿Hay enchufes en la sala de espera?"],
    ["过安检时要取出电脑吗？", "¿Tengo que sacar el ordenador en el control de seguridad?"],
    ["请帮我确认一下登机口。", "¿Puede confirmarme la puerta de embarque?"],
    ["什么时候开始登机？", "¿Cuándo empieza el embarque?"],
    ["起飞时间推迟了吗？", "¿Se ha retrasado la hora de despegue?"],
    ["登机时间是几点？", "¿A qué hora es el embarque?"],
    ["我的安全带扣不上。", "No consigo abrocharme el cinturón de seguridad."],
    ["我已经在线提交了海关申报。", "Ya he presentado la declaración de aduanas por internet."],
    ["我需要申报这些物品吗？", "¿Tengo que declarar estos artículos en la aduana?"],
    ["持中国护照应该走哪条入境通道？", "¿Qué fila debo seguir para entrar con pasaporte chino?"],
    ["预计几点着陆？", "¿A qué hora está previsto el aterrizaje?"],
    ["还需要填写入境卡吗？", "¿Todavía hay que rellenar una tarjeta de entrada?"],
    ["可以帮我填写海关申报单吗？", "¿Puede ayudarme a rellenar la declaración de aduanas?"],
    ["非欧盟护照应该排哪一队？", "¿Qué cola es para pasaportes de fuera de la Unión Europea?"]
  ],
  transport: [
    ["可以直接刷非接触式银行卡乘车吗？", "¿Puedo pagar el viaje directamente con una tarjeta sin contacto?"],
    ["去市中心应该在哪一站下车？", "¿En qué estación tengo que bajarme para ir al centro?"],
    ["去马德里的车从哪个站台出发？", "¿De qué andén sale el tren a Madrid?"],
    ["下一班车几点出发？", "¿A qué hora sale el próximo servicio?"],
    ["请给我一张去托莱多的单程票。", "Un billete de ida a Toledo, por favor."],
    ["最近的地铁入口在哪里？", "¿Dónde está la entrada de metro más cercana?"],
    ["这辆公交车去机场吗？", "¿Este autobús va al aeropuerto?"],
    ["我需要换乘地铁吗？", "¿Tengo que hacer transbordo en el metro?"],
    ["公交车票可以上车后买吗？", "¿Se puede comprar el billete dentro del autobús?"],
    ["最后一班地铁是几点？", "¿A qué hora pasa el último metro?"],
    ["去塞维利亚的火车在哪里乘坐？", "¿Dónde se coge el tren a Sevilla?"],
    ["我错过了高铁，可以改签吗？", "He perdido el tren de alta velocidad, ¿puedo cambiar el billete?"],
    ["这趟火车需要预订座位吗？", "¿Hay que reservar asiento en este tren?"],
    ["这是直达高铁吗？", "¿Es un tren de alta velocidad directo?"],
    ["火车会在哪些车站停靠？", "¿En qué estaciones para el tren?"],
    ["网约车上车点在哪里？", "¿Dónde está la zona de recogida de vehículos con conductor?"],
    ["可以帮我叫一辆出租车吗？", "¿Puede llamarme un taxi?"],
    ["出租车可以刷卡吗？", "¿Se puede pagar el taxi con tarjeta?"],
    ["请打表。", "Ponga el taxímetro, por favor."],
    ["请开到这个地址。", "Lléveme a esta dirección, por favor."],
    ["到机场大约多少钱？", "¿Cuánto cuesta aproximadamente ir al aeropuerto?"],
    ["在哪里办理租车手续？", "¿Dónde se recoge el coche de alquiler?"],
    ["最近的加油站在哪里？", "¿Dónde está la gasolinera más cercana?"],
    ["这里可以停车吗？", "¿Se puede aparcar aquí?"],
    ["在红绿灯处右转。", "Gire a la derecha en el semáforo."],
    ["这辆车用汽油还是柴油？", "¿Este coche usa gasolina o diésel?"],
    ["我预订了一辆租赁汽车。", "Tengo reservado un coche de alquiler."],
    ["请加满九五号汽油。", "Llene el depósito de gasolina sin plomo 95, por favor."],
    ["停车费在哪里支付？", "¿Dónde se paga el aparcamiento?"],
    ["过了红绿灯就是入口。", "La entrada está justo después del semáforo."]
  ],
  hotel: [
    ["请问酒店前台在哪里？", "¿Dónde está la recepción del hotel?"],
    ["我想预订一家国营古堡酒店。", "Quisiera reservar una habitación en un parador."],
    ["这家旅游住宿可以寄存行李吗？", "¿Puedo dejar el equipaje en este alojamiento turístico?"],
    ["我可以在前台办理入住吗？", "¿Puedo registrarme en recepción?"],
    ["请帮我查一下这个姓名下的预订。", "¿Puede buscar la reserva a este nombre?"],
    ["最早几点可以入住？", "¿A partir de qué hora se puede entrar en la habitación?"],
    ["我把房间钥匙弄丢了。", "He perdido la llave de la habitación."],
    ["我的房卡失效了。", "La tarjeta de mi habitación no funciona."],
    ["可以请人帮我拿行李吗？", "¿Puede el botones ayudarme con el equipaje?"],
    ["我需要找一位工作人员。", "Necesito hablar con alguien del personal."],
    ["可以再送两条毛巾吗？", "¿Me pueden traer dos toallas más?"],
    ["请更换一下床单。", "¿Pueden cambiar las sábanas, por favor?"],
    ["可以再给我一个枕头吗？", "¿Me puede traer otra almohada?"],
    ["被子不够暖和。", "El edredón no abriga lo suficiente."],
    ["可以晚一点退房吗？", "¿Podría dejar la habitación un poco más tarde?"],
    ["今天不用打扫房间。", "Hoy no hace falta limpiar la habitación."],
    ["请明早七点叫醒我。", "Quisiera el servicio de despertador a las siete."],
    ["洗衣服务什么时候送回来？", "¿Cuándo devuelven la ropa del servicio de lavandería?"],
    ["房间里有熨斗吗？", "¿Hay una plancha en la habitación?"],
    ["可以在房间里加一张婴儿床吗？", "¿Pueden poner una cuna en la habitación?"],
    ["今晚所有房型都满了吗？", "¿Están ocupadas todas las habitaciones para esta noche?"],
    ["烟雾报警器一直在响。", "El detector de humo no deja de sonar."],
    ["这一层的灭火器在哪里？", "¿Dónde está el extintor de esta planta?"],
    ["我想要一间朝内院的安静房间。", "Quisiera una habitación tranquila que dé al patio."],
    ["隔壁房间太吵了。", "La habitación de al lado hace demasiado ruido."],
    ["周末也已经满房了吗？", "¿También está completo el hotel este fin de semana?"],
    ["我现在想办理退房。", "Quisiera dejar la habitación ahora."],
    ["请帮我确认退房时间。", "¿Puede confirmarme la hora de salida?"],
    ["可以给我一张正式收据吗？", "¿Me puede dar un recibo oficial?"],
    ["请帮我核对一下账单。", "¿Puede revisar la cuenta conmigo?"]
  ],
  food: [
    ["早餐几点开始供应？", "¿A qué hora empieza el desayuno?"],
    ["午餐有每日套餐吗？", "¿Hay menú del día para la comida?"],
    ["我想预订今晚八点的晚餐。", "Quisiera reservar una mesa para cenar a las ocho."],
    ["劳驾，我们可以点餐了吗？", "Perdone, ¿podemos pedir ya?"],
    ["请给我看一下菜单。", "¿Me trae la carta, por favor?"],
    ["米饭可以换成沙拉吗？", "¿Puedo cambiar el arroz por una ensalada?"],
    ["可以再给我们一些面包吗？", "¿Nos trae un poco más de pan?"],
    ["剩下的可以打包吗？", "¿Me puede poner lo que queda para llevar?"],
    ["请给我一瓶不带气的水。", "Una botella de agua sin gas, por favor."],
    ["可以给我一杯热水吗？", "¿Me puede traer un vaso de agua caliente?"],
    ["你们有什么茶？", "¿Qué tipos de té tienen?"],
    ["请给我一杯少量牛奶的咖啡。", "Un café cortado, por favor."],
    ["有不含乳糖的牛奶吗？", "¿Tienen leche sin lactosa?"],
    ["这道菜可以少放盐吗？", "¿Pueden preparar este plato con poca sal?"],
    ["咖啡请不要加糖。", "El café sin azúcar, por favor."],
    ["有不含酱油的菜吗？", "¿Hay algún plato sin salsa de soja?"],
    ["请另外给我一点醋。", "¿Me trae un poco de vinagre aparte?"],
    ["请不要放胡椒。", "Sin pimienta, por favor."],
    ["可以给我一双筷子吗？", "¿Me puede traer unos palillos?"],
    ["汤匙掉到地上了，可以换一把吗？", "Se me ha caído la cuchara, ¿me trae otra?"],
    ["可以再给我一把叉子吗？", "¿Me trae otro tenedor?"],
    ["牛排刀不太锋利。", "Este cuchillo no corta bien la carne."],
    ["味噌汤里有鱼吗？", "¿La sopa de miso lleva pescado?"],
    ["这个鸡蛋是全熟的吗？", "¿El huevo está bien hecho?"],
    ["我不吃肉。", "No como carne."],
    ["牛肉请做全熟。", "La ternera bien hecha, por favor."],
    ["服务费已经包含在账单里了吗？", "¿Está incluido el servicio en la cuenta?"],
    ["我们在哪里付款？", "¿Dónde se paga?"],
    ["麻烦把账单拿给我们。", "¿Nos trae la cuenta, por favor?"],
    ["可以在收银台分开付款吗？", "¿Podemos pagar por separado en la caja?"]
  ],
  shopping: [
    ["请问商店入口在哪里？", "¿Dónde está la entrada de la tienda?"],
    ["百货商店今天营业吗？", "¿Abren hoy los grandes almacenes?"],
    ["这附近有大型超市吗？", "¿Hay algún supermercado grande cerca?"],
    ["便利店是二十四小时营业吗？", "¿La tienda de conveniencia abre las veinticuatro horas?"],
    ["周末市场几点开始？", "¿A qué hora empieza el mercado el fin de semana?"],
    ["这件衣服有我的尺码吗？", "¿Tiene esta prenda en mi talla?"],
    ["可以给我大一码的吗？", "¿Me puede dar una talla más grande?"],
    ["这件是中码吗？", "¿Esta es la talla mediana?"],
    ["有没有小一码的？", "¿Tiene una talla más pequeña?"],
    ["可以帮我量一下尺码吗？", "¿Puede ayudarme a elegir la talla?"],
    ["试衣间在哪里？", "¿Dónde están los probadores?"],
    ["我可以试穿这件外套吗？", "¿Me puedo probar este abrigo?"],
    ["试衣间需要排队吗？", "¿Hay que hacer cola para el probador?"],
    ["试穿后放在哪里？", "¿Dónde dejo la ropa después de probármela?"],
    ["试衣间里最多可以拿几件？", "¿Cuántas prendas puedo llevar al probador?"],
    ["请问这件商品多少钱？", "¿Cuánto cuesta este artículo?"],
    ["标签上标的是最终价格吗？", "¿El precio de la etiqueta es el precio final?"],
    ["这个对我来说太贵了。", "Esto es demasiado caro para mí."],
    ["有没有更便宜的款式？", "¿Tiene algún modelo más barato?"],
    ["标价包含增值税吗？", "¿El precio incluye el IVA?"],
    ["可以用信用卡付款吗？", "¿Puedo pagar con tarjeta de crédito?"],
    ["这张银行卡为什么不能用？", "¿Por qué no funciona esta tarjeta bancaria?"],
    ["可以找开五十欧元吗？", "¿Tiene cambio de cincuenta euros?"],
    ["请把购物小票给我。", "¿Me da el tique, por favor?"],
    ["退货时需要购物小票吗？", "¿Hace falta el tique para devolverlo?"],
    ["小票上的价格不对。", "El precio del tique no es correcto."],
    ["我把购物小票弄丢了。", "He perdido el tique de compra."],
    ["可以重新打印小票吗？", "¿Puede volver a imprimir el tique?"],
    ["小票上没有显示折扣。", "El descuento no aparece en el tique."],
    ["可以给我一张用于退税的发票吗？", "¿Puede darme una factura para solicitar la devolución del IVA?"]
  ],
  directions: [
    ["请问游客服务中心在哪里？", "¿Dónde está la oficina de turismo?"],
    ["我们现在是在地图上的这里吗？", "¿Estamos aquí en el mapa?"],
    ["您说的是那边那栋楼吗？", "¿Se refiere a aquel edificio de allí?"],
    ["下一个路口要左转吗？", "¿Tengo que girar a la izquierda en el próximo cruce?"],
    ["车站在道路右侧吗？", "¿La estación está a la derecha?"],
    ["博物馆就在我们前面吗？", "¿Está el museo justo delante de nosotros?"],
    ["停车场在酒店后面。", "El aparcamiento está detrás del hotel."],
    ["药店就在银行旁边。", "La farmacia está al lado del banco."],
    ["邮局在公园对面。", "Correos está enfrente del parque."],
    ["附近有地铁站吗？", "¿Hay alguna estación de metro cerca?"],
    ["机场离这里有多远？", "¿A qué distancia está el aeropuerto?"],
    ["走路很近吗？", "¿Está cerca para ir andando?"],
    ["坐公交车去很远吗？", "¿Está lejos para ir en autobús?"],
    ["最近的药店是哪一家？", "¿Cuál es la farmacia más cercana?"],
    ["车站很远，最好坐地铁。", "La estación está lejos; es mejor ir en metro."],
    ["这附近有什么景点？", "¿Qué lugares de interés hay cerca?"],
    ["步行过去会不会太远？", "¿Está demasiado lejos para ir a pie?"],
    ["最近的公共洗手间在哪里？", "¿Dónde está el aseo público más cercano?"],
    ["过桥后向左转。", "Después de cruzar el puente, gire a la izquierda."],
    ["这条路通往市中心吗？", "¿Esta carretera lleva al centro?"],
    ["这条街叫什么名字？", "¿Cómo se llama esta calle?"],
    ["我要找的是一栋白色建筑。", "Busco un edificio blanco."],
    ["最近的银行几点关门？", "¿A qué hora cierra el banco más cercano?"],
    ["邮局离这里远吗？", "¿Está lejos la oficina de Correos?"],
    ["这附近有公共厕所吗？", "¿Hay algún aseo público por aquí?"],
    ["哪一站是公交车站？", "¿Dónde está la parada de autobús?"],
    ["最近的地铁站有电梯吗？", "¿La estación de metro más cercana tiene ascensor?"],
    ["可以推荐一个附近的景点吗？", "¿Me recomienda algún lugar turístico cercano?"],
    ["今天博物馆开门吗？", "¿Está abierto hoy el museo?"],
    ["从这里怎么去公园？", "¿Cómo se llega al parque desde aquí?"]
  ],
  emergency: [
    ["我发烧了，需要看医生。", "Tengo fiebre y necesito ver a un médico."],
    ["我感冒了，哪里有药店？", "Estoy resfriado, ¿dónde hay una farmacia?"],
    ["这种咳嗽药一天吃几次？", "¿Cuántas veces al día se toma este medicamento para la tos?"],
    ["我头疼得很厉害。", "Me duele mucho la cabeza."],
    ["我从昨晚开始胃痛。", "Me duele el estómago desde anoche."],
    ["附近有值班药店吗？", "¿Hay alguna farmacia de guardia cerca?"],
    ["可以请护士来看一下吗？", "¿Puede venir un enfermero a verme?"],
    ["这种药需要处方吗？", "¿Hace falta receta para este medicamento?"],
    ["在哪里可以配这张处方？", "¿Dónde puedo comprar lo que indica esta receta?"],
    ["这药片需要饭后吃吗？", "¿Tengo que tomar esta pastilla después de comer?"],
    ["这种药膏一天涂几次？", "¿Cuántas veces al día tengo que aplicar esta pomada?"],
    ["我的手机丢了，需要报警。", "He perdido el móvil y necesito denunciarlo."],
    ["我应该去哪个警察局报案？", "¿En qué comisaría puedo presentar la denuncia?"],
    ["我需要一份报案证明。", "Necesito una copia de la denuncia."],
    ["有人偷了我的背包。", "Me han robado la mochila."],
    ["请帮我联系警察。", "Ayúdeme a contactar con la policía, por favor."],
    ["我腹泻了两天。", "Tengo diarrea desde hace dos días."],
    ["这种药会引起便秘吗？", "¿Este medicamento puede causar estreñimiento?"],
    ["伤口需要缝针吗？", "¿Hay que dar puntos en la herida?"],
    ["伤口还在流血。", "La herida sigue sangrando."],
    ["我可能骨折了。", "Creo que tengo una fractura."],
    ["救命，有人昏倒了！", "¡Socorro, alguien se ha desmayado!"],
    ["这里有人需要紧急帮助。", "Aquí hay alguien que necesita ayuda urgente."],
    ["请拨打112叫救护车。", "Llame al 112 y pida una ambulancia, por favor."],
    ["我摔倒后受伤了。", "Me he hecho daño al caerme."],
    ["怎样才能止血？", "¿Cómo puedo detener el sangrado?"],
    ["我的旅行保险涵盖这项治疗吗？", "¿Mi seguro de viaje cubre este tratamiento?"],
    ["这是我的保险卡。", "Esta es mi tarjeta del seguro."],
    ["保险公司需要一份医疗报告。", "La aseguradora necesita un informe médico."],
    ["可以在报告中写上我的保险号码吗？", "¿Puede incluir mi número de seguro en el informe?"]
  ],
  basics: [
    ["你好，请问你会说英语吗？", "Hola, ¿habla inglés?"],
    ["早上好，我有一个预订。", "Buenos días, tengo una reserva."],
    ["晚上好，还有空桌吗？", "Buenas tardes, ¿queda alguna mesa libre?"],
    ["谢谢您的帮助。", "Gracias por su ayuda."],
    ["真的非常感谢。", "Muchísimas gracias."],
    ["不客气，祝您愉快。", "De nada, que tenga un buen día."],
    ["劳驾，请给我一张地图。", "Un mapa, por favor."],
    ["请给我七张票。", "Siete billetes, por favor."],
    ["我们八点见。", "Nos vemos a las ocho."],
    ["火车从九号站台出发。", "El tren sale del andén nueve."],
    ["步行需要十分钟。", "Se tarda diez minutos andando."],
    ["可以把地址发到我的手机上吗？", "¿Puede enviarme la dirección al móvil?"],
    ["这个小镇有一千多年的历史。", "Este pueblo tiene más de mil años de historia."],
    ["这里大约有一万人。", "Aquí viven unas diez mil personas."],
    ["这里可以把日元换成欧元吗？", "¿Puedo cambiar yenes por euros aquí?"],
    ["我想把美元换成欧元。", "Quiero cambiar dólares por euros."],
    ["可以把人民币换成欧元吗？", "¿Se pueden cambiar yuanes por euros?"],
    ["费用是零欧元。", "El coste es de cero euros."],
    ["请给我一张票。", "Un billete, por favor."],
    ["我们要两间房。", "Queremos dos habitaciones."],
    ["今天是星期几？", "¿En qué día de la semana estamos?"],
    ["我们明天去格拉纳达。", "Mañana vamos a Granada."],
    ["我昨天到的。", "Llegué ayer."],
    ["我们后天回来。", "Volvemos pasado mañana."],
    ["是的，我有预订。", "Sí, tengo una reserva."],
    ["不，谢谢。", "No, gracias."],
    ["好的，我们走吧。", "Vale, vamos."],
    ["我想要靠窗的座位。", "Quiero un asiento junto a la ventanilla."],
    ["我需要一名医生。", "Necesito un médico."],
    ["附近有药店吗？", "¿Hay una farmacia cerca?"]
  ]
};
